//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for airportWeatherIntensityProximityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="airportWeatherIntensityProximityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="light"/>
 *     &lt;enumeration value="moderate"/>
 *     &lt;enumeration value="heavy"/>
 *     &lt;enumeration value="in the vicinity"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "airportWeatherIntensityProximityType")
@XmlEnum
public enum AirportWeatherIntensityProximityType {

    @XmlEnumValue("light")
    LIGHT("light"),
    @XmlEnumValue("moderate")
    MODERATE("moderate"),
    @XmlEnumValue("heavy")
    HEAVY("heavy"),
    @XmlEnumValue("in the vicinity")
    IN_THE_VICINITY("in the vicinity");
    private final String value;

    AirportWeatherIntensityProximityType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AirportWeatherIntensityProximityType fromValue(String v) {
        for (AirportWeatherIntensityProximityType c: AirportWeatherIntensityProximityType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
