//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Airport type: either icao code, or iata code, or both
 * 
 * <p>Java class for AirportFullIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirportFullIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="AirportICAOCode" type="{http://aeec.aviation-ia.net/633}AirportICAOCodeType"/>
 *           &lt;element name="AirportIATACode" type="{http://aeec.aviation-ia.net/633}AirportIATACodeType" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element name="AirportIATACode" type="{http://aeec.aviation-ia.net/633}AirportIATACodeType"/>
 *       &lt;/choice>
 *       &lt;attribute name="airportName">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="preserve"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="airportFunction" use="required" type="{http://aeec.aviation-ia.net/633}airportFunctionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirportFullIdentificationType", propOrder = {
    "content"
})
public class AirportFullIdentificationType {

    @XmlElementRefs({
        @XmlElementRef(name = "AirportIATACode", namespace = "http://aeec.aviation-ia.net/633", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AirportICAOCode", namespace = "http://aeec.aviation-ia.net/633", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<String>> content;
    @XmlAttribute(name = "airportName")
    protected String airportName;
    @XmlAttribute(name = "airportFunction", required = true)
    protected AirportFunctionType airportFunction;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "AirportIATACode" is used by two different parts of a schema. See: 
     * line 1232 of file:/Users/oleg.ponomaryov/Downloads/xsd/m633common/m633common.xsd
     * line 1226 of file:/Users/oleg.ponomaryov/Downloads/xsd/m633common/m633common.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<String>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the airportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportName() {
        return airportName;
    }

    /**
     * Sets the value of the airportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportName(String value) {
        this.airportName = value;
    }

    /**
     * Gets the value of the airportFunction property.
     * 
     * @return
     *     possible object is
     *     {@link AirportFunctionType }
     *     
     */
    public AirportFunctionType getAirportFunction() {
        return airportFunction;
    }

    /**
     * Sets the value of the airportFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportFunctionType }
     *     
     */
    public void setAirportFunction(AirportFunctionType value) {
        this.airportFunction = value;
    }

}
