//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AltitudeInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AltitudeInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Altitude" type="{http://aeec.aviation-ia.net/633}AltitudeType" maxOccurs="unbounded"/>
 *         &lt;sequence>
 *           &lt;element name="Upper" type="{http://aeec.aviation-ia.net/633}AltitudeType"/>
 *           &lt;element name="Lower" type="{http://aeec.aviation-ia.net/633}AltitudeType"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AltitudeInfoType", propOrder = {
    "altitude",
    "upper",
    "lower"
})
@XmlSeeAlso({
    com.jeppesen.gs.otsas.xml.RouteDefinitionType.VerticalRoute.Altitudes.class
})
public class AltitudeInfoType {

    @XmlElement(name = "Altitude")
    protected List<AltitudeType> altitude;
    @XmlElement(name = "Upper")
    protected AltitudeType upper;
    @XmlElement(name = "Lower")
    protected AltitudeType lower;

    /**
     * Gets the value of the altitude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altitude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltitude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltitudeType }
     * 
     * 
     */
    public List<AltitudeType> getAltitude() {
        if (altitude == null) {
            altitude = new ArrayList<AltitudeType>();
        }
        return this.altitude;
    }

    /**
     * Gets the value of the upper property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeType }
     *     
     */
    public AltitudeType getUpper() {
        return upper;
    }

    /**
     * Sets the value of the upper property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeType }
     *     
     */
    public void setUpper(AltitudeType value) {
        this.upper = value;
    }

    /**
     * Gets the value of the lower property.
     * 
     * @return
     *     possible object is
     *     {@link AltitudeType }
     *     
     */
    public AltitudeType getLower() {
        return lower;
    }

    /**
     * Sets the value of the lower property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltitudeType }
     *     
     */
    public void setLower(AltitudeType value) {
        this.lower = value;
    }

}
