//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for brakingActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="brakingActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="nil"/>
 *     &lt;enumeration value="poor"/>
 *     &lt;enumeration value="medium to poor"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="medium to good"/>
 *     &lt;enumeration value="good"/>
 *     &lt;enumeration value="unreliable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "brakingActionType")
@XmlEnum
public enum BrakingActionType {

    @XmlEnumValue("nil")
    NIL("nil"),
    @XmlEnumValue("poor")
    POOR("poor"),
    @XmlEnumValue("medium to poor")
    MEDIUM_TO_POOR("medium to poor"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("medium to good")
    MEDIUM_TO_GOOD("medium to good"),
    @XmlEnumValue("good")
    GOOD("good"),
    @XmlEnumValue("unreliable")
    UNRELIABLE("unreliable");
    private final String value;

    BrakingActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BrakingActionType fromValue(String v) {
        for (BrakingActionType c: BrakingActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
