//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CloudsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloudsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="SkyClear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="NilSignificantClouds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;sequence>
 *             &lt;element name="VerticalVisibility" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
 *             &lt;element name="CloudDescriptions">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="CloudDescription" maxOccurs="unbounded">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="Ceiling" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
 *                               &lt;/sequence>
 *                               &lt;attribute name="cloudCover" use="required">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;minLength value="1"/>
 *                                     &lt;whiteSpace value="preserve"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/attribute>
 *                               &lt;attribute name="cloudType">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;enumeration value="CB"/>
 *                                     &lt;enumeration value="TCU"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/attribute>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CloudsType", propOrder = {
    "skyClear",
    "nilSignificantClouds",
    "verticalVisibility",
    "cloudDescriptions"
})
public class CloudsType {

    @XmlElement(name = "SkyClear")
    protected String skyClear;
    @XmlElement(name = "NilSignificantClouds")
    protected String nilSignificantClouds;
    @XmlElement(name = "VerticalVisibility")
    protected DistanceType verticalVisibility;
    @XmlElement(name = "CloudDescriptions")
    protected CloudsType.CloudDescriptions cloudDescriptions;

    /**
     * Gets the value of the skyClear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkyClear() {
        return skyClear;
    }

    /**
     * Sets the value of the skyClear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkyClear(String value) {
        this.skyClear = value;
    }

    /**
     * Gets the value of the nilSignificantClouds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNilSignificantClouds() {
        return nilSignificantClouds;
    }

    /**
     * Sets the value of the nilSignificantClouds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNilSignificantClouds(String value) {
        this.nilSignificantClouds = value;
    }

    /**
     * Gets the value of the verticalVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceType }
     *     
     */
    public DistanceType getVerticalVisibility() {
        return verticalVisibility;
    }

    /**
     * Sets the value of the verticalVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceType }
     *     
     */
    public void setVerticalVisibility(DistanceType value) {
        this.verticalVisibility = value;
    }

    /**
     * Gets the value of the cloudDescriptions property.
     * 
     * @return
     *     possible object is
     *     {@link CloudsType.CloudDescriptions }
     *     
     */
    public CloudsType.CloudDescriptions getCloudDescriptions() {
        return cloudDescriptions;
    }

    /**
     * Sets the value of the cloudDescriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CloudsType.CloudDescriptions }
     *     
     */
    public void setCloudDescriptions(CloudsType.CloudDescriptions value) {
        this.cloudDescriptions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CloudDescription" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Ceiling" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="cloudCover" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                       &lt;whiteSpace value="preserve"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="cloudType">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="CB"/>
     *                       &lt;enumeration value="TCU"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cloudDescription"
    })
    public static class CloudDescriptions {

        @XmlElement(name = "CloudDescription", required = true)
        protected List<CloudsType.CloudDescriptions.CloudDescription> cloudDescription;

        /**
         * Gets the value of the cloudDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cloudDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCloudDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CloudsType.CloudDescriptions.CloudDescription }
         * 
         * 
         */
        public List<CloudsType.CloudDescriptions.CloudDescription> getCloudDescription() {
            if (cloudDescription == null) {
                cloudDescription = new ArrayList<CloudsType.CloudDescriptions.CloudDescription>();
            }
            return this.cloudDescription;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Ceiling" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="cloudCover" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *             &lt;whiteSpace value="preserve"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="cloudType">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="CB"/>
         *             &lt;enumeration value="TCU"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ceiling"
        })
        public static class CloudDescription {

            @XmlElement(name = "Ceiling")
            protected DistanceType ceiling;
            @XmlAttribute(name = "cloudCover", required = true)
            protected String cloudCover;
            @XmlAttribute(name = "cloudType")
            protected String cloudType;

            /**
             * Gets the value of the ceiling property.
             * 
             * @return
             *     possible object is
             *     {@link DistanceType }
             *     
             */
            public DistanceType getCeiling() {
                return ceiling;
            }

            /**
             * Sets the value of the ceiling property.
             * 
             * @param value
             *     allowed object is
             *     {@link DistanceType }
             *     
             */
            public void setCeiling(DistanceType value) {
                this.ceiling = value;
            }

            /**
             * Gets the value of the cloudCover property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCloudCover() {
                return cloudCover;
            }

            /**
             * Sets the value of the cloudCover property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCloudCover(String value) {
                this.cloudCover = value;
            }

            /**
             * Gets the value of the cloudType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCloudType() {
                return cloudType;
            }

            /**
             * Sets the value of the cloudType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCloudType(String value) {
                this.cloudType = value;
            }

        }

    }

}
