//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines Passenger Connection information
 * 
 * <p>Java class for ConnectionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncomingFlights" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IncomingFlight" type="{http://aeec.aviation-ia.net/633}FlightType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OutgoingFlights" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OutgoingFlight" type="{http://aeec.aviation-ia.net/633}FlightType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectionInfoType", propOrder = {
    "incomingFlights",
    "outgoingFlights"
})
public class ConnectionInfoType {

    @XmlElement(name = "IncomingFlights")
    protected ConnectionInfoType.IncomingFlights incomingFlights;
    @XmlElement(name = "OutgoingFlights")
    protected ConnectionInfoType.OutgoingFlights outgoingFlights;

    /**
     * Gets the value of the incomingFlights property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionInfoType.IncomingFlights }
     *     
     */
    public ConnectionInfoType.IncomingFlights getIncomingFlights() {
        return incomingFlights;
    }

    /**
     * Sets the value of the incomingFlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionInfoType.IncomingFlights }
     *     
     */
    public void setIncomingFlights(ConnectionInfoType.IncomingFlights value) {
        this.incomingFlights = value;
    }

    /**
     * Gets the value of the outgoingFlights property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionInfoType.OutgoingFlights }
     *     
     */
    public ConnectionInfoType.OutgoingFlights getOutgoingFlights() {
        return outgoingFlights;
    }

    /**
     * Sets the value of the outgoingFlights property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionInfoType.OutgoingFlights }
     *     
     */
    public void setOutgoingFlights(ConnectionInfoType.OutgoingFlights value) {
        this.outgoingFlights = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IncomingFlight" type="{http://aeec.aviation-ia.net/633}FlightType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "incomingFlight"
    })
    public static class IncomingFlights {

        @XmlElement(name = "IncomingFlight", required = true)
        protected List<FlightType> incomingFlight;

        /**
         * Gets the value of the incomingFlight property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the incomingFlight property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncomingFlight().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightType }
         * 
         * 
         */
        public List<FlightType> getIncomingFlight() {
            if (incomingFlight == null) {
                incomingFlight = new ArrayList<FlightType>();
            }
            return this.incomingFlight;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OutgoingFlight" type="{http://aeec.aviation-ia.net/633}FlightType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outgoingFlight"
    })
    public static class OutgoingFlights {

        @XmlElement(name = "OutgoingFlight", required = true)
        protected List<FlightType> outgoingFlight;

        /**
         * Gets the value of the outgoingFlight property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the outgoingFlight property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOutgoingFlight().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightType }
         * 
         * 
         */
        public List<FlightType> getOutgoingFlight() {
            if (outgoingFlight == null) {
                outgoingFlight = new ArrayList<FlightType>();
            }
            return this.outgoingFlight;
        }

    }

}
