//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtraFuelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExtraFuelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AirTrafficControl"/>
 *     &lt;enumeration value="BallastFuel"/>
 *     &lt;enumeration value="Deviation"/>
 *     &lt;enumeration value="DispatchDefined"/>
 *     &lt;enumeration value="FuelOnBoard"/>
 *     &lt;enumeration value="MinimumLandingWeight"/>
 *     &lt;enumeration value="MinimumReserve"/>
 *     &lt;enumeration value="Operation"/>
 *     &lt;enumeration value="SpecialHolding"/>
 *     &lt;enumeration value="Tankering"/>
 *     &lt;enumeration value="TerrainClearance"/>
 *     &lt;enumeration value="Weather"/>
 *     &lt;enumeration value="AirportWeather"/>
 *     &lt;enumeration value="RegionWeather"/>
 *     &lt;enumeration value="MandatoryTankering"/>
 *     &lt;enumeration value="EconomicTankering"/>
 *     &lt;enumeration value="FuelPadding"/>
 *     &lt;enumeration value="Extra"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExtraFuelType")
@XmlEnum
public enum ExtraFuelType {

    @XmlEnumValue("AirTrafficControl")
    AIR_TRAFFIC_CONTROL("AirTrafficControl"),
    @XmlEnumValue("BallastFuel")
    BALLAST_FUEL("BallastFuel"),
    @XmlEnumValue("Deviation")
    DEVIATION("Deviation"),
    @XmlEnumValue("DispatchDefined")
    DISPATCH_DEFINED("DispatchDefined"),
    @XmlEnumValue("FuelOnBoard")
    FUEL_ON_BOARD("FuelOnBoard"),
    @XmlEnumValue("MinimumLandingWeight")
    MINIMUM_LANDING_WEIGHT("MinimumLandingWeight"),
    @XmlEnumValue("MinimumReserve")
    MINIMUM_RESERVE("MinimumReserve"),
    @XmlEnumValue("Operation")
    OPERATION("Operation"),
    @XmlEnumValue("SpecialHolding")
    SPECIAL_HOLDING("SpecialHolding"),
    @XmlEnumValue("Tankering")
    TANKERING("Tankering"),
    @XmlEnumValue("TerrainClearance")
    TERRAIN_CLEARANCE("TerrainClearance"),
    @XmlEnumValue("Weather")
    WEATHER("Weather"),
    @XmlEnumValue("AirportWeather")
    AIRPORT_WEATHER("AirportWeather"),
    @XmlEnumValue("RegionWeather")
    REGION_WEATHER("RegionWeather"),
    @XmlEnumValue("MandatoryTankering")
    MANDATORY_TANKERING("MandatoryTankering"),
    @XmlEnumValue("EconomicTankering")
    ECONOMIC_TANKERING("EconomicTankering"),
    @XmlEnumValue("FuelPadding")
    FUEL_PADDING("FuelPadding"),
    @XmlEnumValue("Extra")
    EXTRA("Extra");
    private final String value;

    ExtraFuelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExtraFuelType fromValue(String v) {
        for (ExtraFuelType c: ExtraFuelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
