//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * flight data allowing to identify the flight
 * 
 * <p>Java class for FlightType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FlightIdentification" type="{http://aeec.aviation-ia.net/633}FlightIdentificationType"/>
 *         &lt;element name="DepartureAirport" type="{http://aeec.aviation-ia.net/633}AirportIdentificationType"/>
 *         &lt;element name="ArrivalAirport" type="{http://aeec.aviation-ia.net/633}AirportIdentificationType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="flightOriginDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="scheduledTimeOfDeparture" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightType", propOrder = {
    "flightIdentification",
    "departureAirport",
    "arrivalAirport"
})
public class FlightType {

    @XmlElement(name = "FlightIdentification", required = true)
    protected FlightIdentificationType flightIdentification;
    @XmlElement(name = "DepartureAirport", required = true)
    protected AirportIdentificationType departureAirport;
    @XmlElement(name = "ArrivalAirport", required = true)
    protected AirportIdentificationType arrivalAirport;
    @XmlAttribute(name = "flightOriginDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar flightOriginDate;
    @XmlAttribute(name = "scheduledTimeOfDeparture")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledTimeOfDeparture;

    /**
     * Gets the value of the flightIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link FlightIdentificationType }
     *     
     */
    public FlightIdentificationType getFlightIdentification() {
        return flightIdentification;
    }

    /**
     * Sets the value of the flightIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightIdentificationType }
     *     
     */
    public void setFlightIdentification(FlightIdentificationType value) {
        this.flightIdentification = value;
    }

    /**
     * Gets the value of the departureAirport property.
     * 
     * @return
     *     possible object is
     *     {@link AirportIdentificationType }
     *     
     */
    public AirportIdentificationType getDepartureAirport() {
        return departureAirport;
    }

    /**
     * Sets the value of the departureAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportIdentificationType }
     *     
     */
    public void setDepartureAirport(AirportIdentificationType value) {
        this.departureAirport = value;
    }

    /**
     * Gets the value of the arrivalAirport property.
     * 
     * @return
     *     possible object is
     *     {@link AirportIdentificationType }
     *     
     */
    public AirportIdentificationType getArrivalAirport() {
        return arrivalAirport;
    }

    /**
     * Sets the value of the arrivalAirport property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportIdentificationType }
     *     
     */
    public void setArrivalAirport(AirportIdentificationType value) {
        this.arrivalAirport = value;
    }

    /**
     * Gets the value of the flightOriginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFlightOriginDate() {
        return flightOriginDate;
    }

    /**
     * Sets the value of the flightOriginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFlightOriginDate(XMLGregorianCalendar value) {
        this.flightOriginDate = value;
    }

    /**
     * Gets the value of the scheduledTimeOfDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledTimeOfDeparture() {
        return scheduledTimeOfDeparture;
    }

    /**
     * Sets the value of the scheduledTimeOfDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledTimeOfDeparture(XMLGregorianCalendar value) {
        this.scheduledTimeOfDeparture = value;
    }

}
