//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flowUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="flowUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kg/h"/>
 *     &lt;enumeration value="kg/s"/>
 *     &lt;enumeration value="lb/h"/>
 *     &lt;enumeration value="lb/s"/>
 *     &lt;enumeration value="kg/mn"/>
 *     &lt;enumeration value="hlb/h"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "flowUnitType")
@XmlEnum
public enum FlowUnitType {

    @XmlEnumValue("kg/h")
    KG_H("kg/h"),
    @XmlEnumValue("kg/s")
    KG_S("kg/s"),
    @XmlEnumValue("lb/h")
    LB_H("lb/h"),
    @XmlEnumValue("lb/s")
    LB_S("lb/s"),
    @XmlEnumValue("kg/mn")
    KG_MN("kg/mn"),
    @XmlEnumValue("hlb/h")
    HLB_H("hlb/h");
    private final String value;

    FlowUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FlowUnitType fromValue(String v) {
        for (FlowUnitType c: FlowUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
