//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FuelAdjustmentReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FuelAdjustmentReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ZeroFuelWeight"/>
 *     &lt;enumeration value="TakeoffWeight"/>
 *     &lt;enumeration value="Altitude"/>
 *     &lt;enumeration value="FL"/>
 *     &lt;enumeration value="CostIndex"/>
 *     &lt;enumeration value="MachNumber"/>
 *     &lt;enumeration value="IndicatedAirSpeed"/>
 *     &lt;enumeration value="TrueAirSpeed"/>
 *     &lt;enumeration value="LRC"/>
 *     &lt;enumeration value="MEC"/>
 *     &lt;enumeration value="MRC"/>
 *     &lt;enumeration value="MSP"/>
 *     &lt;enumeration value="AverageWindComponent"/>
 *     &lt;enumeration value="AverageISADeviation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FuelAdjustmentReasonType")
@XmlEnum
public enum FuelAdjustmentReasonType {

    @XmlEnumValue("ZeroFuelWeight")
    ZERO_FUEL_WEIGHT("ZeroFuelWeight"),
    @XmlEnumValue("TakeoffWeight")
    TAKEOFF_WEIGHT("TakeoffWeight"),
    @XmlEnumValue("Altitude")
    ALTITUDE("Altitude"),
    FL("FL"),
    @XmlEnumValue("CostIndex")
    COST_INDEX("CostIndex"),
    @XmlEnumValue("MachNumber")
    MACH_NUMBER("MachNumber"),
    @XmlEnumValue("IndicatedAirSpeed")
    INDICATED_AIR_SPEED("IndicatedAirSpeed"),
    @XmlEnumValue("TrueAirSpeed")
    TRUE_AIR_SPEED("TrueAirSpeed"),
    LRC("LRC"),
    MEC("MEC"),
    MRC("MRC"),
    MSP("MSP"),
    @XmlEnumValue("AverageWindComponent")
    AVERAGE_WIND_COMPONENT("AverageWindComponent"),
    @XmlEnumValue("AverageISADeviation")
    AVERAGE_ISA_DEVIATION("AverageISADeviation");
    private final String value;

    FuelAdjustmentReasonType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FuelAdjustmentReasonType fromValue(String v) {
        for (FuelAdjustmentReasonType c: FuelAdjustmentReasonType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
