//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeographyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="Polygon">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Coordinates" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
 *                             &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BorderMargin" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Spot">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Coordinates">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Radius" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="MovementSpeed" type="{http://aeec.aviation-ia.net/633}SpeedType" minOccurs="0"/>
 *         &lt;element name="MovementDirection" type="{http://aeec.aviation-ia.net/633}DirectionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographyType", propOrder = {
    "polygon",
    "spot",
    "movementSpeed",
    "movementDirection"
})
public class GeographyType {

    @XmlElement(name = "Polygon")
    protected GeographyType.Polygon polygon;
    @XmlElement(name = "Spot")
    protected GeographyType.Spot spot;
    @XmlElement(name = "MovementSpeed")
    protected SpeedType movementSpeed;
    @XmlElement(name = "MovementDirection")
    protected DirectionType movementDirection;

    /**
     * Gets the value of the polygon property.
     * 
     * @return
     *     possible object is
     *     {@link GeographyType.Polygon }
     *     
     */
    public GeographyType.Polygon getPolygon() {
        return polygon;
    }

    /**
     * Sets the value of the polygon property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographyType.Polygon }
     *     
     */
    public void setPolygon(GeographyType.Polygon value) {
        this.polygon = value;
    }

    /**
     * Gets the value of the spot property.
     * 
     * @return
     *     possible object is
     *     {@link GeographyType.Spot }
     *     
     */
    public GeographyType.Spot getSpot() {
        return spot;
    }

    /**
     * Sets the value of the spot property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographyType.Spot }
     *     
     */
    public void setSpot(GeographyType.Spot value) {
        this.spot = value;
    }

    /**
     * Gets the value of the movementSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link SpeedType }
     *     
     */
    public SpeedType getMovementSpeed() {
        return movementSpeed;
    }

    /**
     * Sets the value of the movementSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpeedType }
     *     
     */
    public void setMovementSpeed(SpeedType value) {
        this.movementSpeed = value;
    }

    /**
     * Gets the value of the movementDirection property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionType }
     *     
     */
    public DirectionType getMovementDirection() {
        return movementDirection;
    }

    /**
     * Sets the value of the movementDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionType }
     *     
     */
    public void setMovementDirection(DirectionType value) {
        this.movementDirection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Coordinates" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
     *                 &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BorderMargin" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "coordinates",
        "borderMargin"
    })
    public static class Polygon {

        @XmlElement(name = "Coordinates", required = true)
        protected List<GeographyType.Polygon.Coordinates> coordinates;
        @XmlElement(name = "BorderMargin")
        protected DistanceType borderMargin;

        /**
         * Gets the value of the coordinates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the coordinates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCoordinates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeographyType.Polygon.Coordinates }
         * 
         * 
         */
        public List<GeographyType.Polygon.Coordinates> getCoordinates() {
            if (coordinates == null) {
                coordinates = new ArrayList<GeographyType.Polygon.Coordinates>();
            }
            return this.coordinates;
        }

        /**
         * Gets the value of the borderMargin property.
         * 
         * @return
         *     possible object is
         *     {@link DistanceType }
         *     
         */
        public DistanceType getBorderMargin() {
            return borderMargin;
        }

        /**
         * Sets the value of the borderMargin property.
         * 
         * @param value
         *     allowed object is
         *     {@link DistanceType }
         *     
         */
        public void setBorderMargin(DistanceType value) {
            this.borderMargin = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
         *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Coordinates {

            @XmlAttribute(name = "sequence")
            @XmlSchemaType(name = "nonNegativeInteger")
            protected BigInteger sequence;
            @XmlAttribute(name = "latitude", required = true)
            protected float latitude;
            @XmlAttribute(name = "longitude", required = true)
            protected float longitude;
            @XmlAttribute(name = "magneticVariation")
            protected Float magneticVariation;

            /**
             * Gets the value of the sequence property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSequence() {
                return sequence;
            }

            /**
             * Sets the value of the sequence property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSequence(BigInteger value) {
                this.sequence = value;
            }

            /**
             * Gets the value of the latitude property.
             * 
             */
            public float getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             */
            public void setLatitude(float value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             */
            public float getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             */
            public void setLongitude(float value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the magneticVariation property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getMagneticVariation() {
                return magneticVariation;
            }

            /**
             * Sets the value of the magneticVariation property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setMagneticVariation(Float value) {
                this.magneticVariation = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Coordinates">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Radius" type="{http://aeec.aviation-ia.net/633}DistanceType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "coordinates",
        "radius"
    })
    public static class Spot {

        @XmlElement(name = "Coordinates", required = true)
        protected GeographyType.Spot.Coordinates coordinates;
        @XmlElement(name = "Radius")
        protected DistanceType radius;

        /**
         * Gets the value of the coordinates property.
         * 
         * @return
         *     possible object is
         *     {@link GeographyType.Spot.Coordinates }
         *     
         */
        public GeographyType.Spot.Coordinates getCoordinates() {
            return coordinates;
        }

        /**
         * Sets the value of the coordinates property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeographyType.Spot.Coordinates }
         *     
         */
        public void setCoordinates(GeographyType.Spot.Coordinates value) {
            this.coordinates = value;
        }

        /**
         * Gets the value of the radius property.
         * 
         * @return
         *     possible object is
         *     {@link DistanceType }
         *     
         */
        public DistanceType getRadius() {
            return radius;
        }

        /**
         * Sets the value of the radius property.
         * 
         * @param value
         *     allowed object is
         *     {@link DistanceType }
         *     
         */
        public void setRadius(DistanceType value) {
            this.radius = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Coordinates {

            @XmlAttribute(name = "latitude", required = true)
            protected float latitude;
            @XmlAttribute(name = "longitude", required = true)
            protected float longitude;
            @XmlAttribute(name = "magneticVariation")
            protected Float magneticVariation;

            /**
             * Gets the value of the latitude property.
             * 
             */
            public float getLatitude() {
                return latitude;
            }

            /**
             * Sets the value of the latitude property.
             * 
             */
            public void setLatitude(float value) {
                this.latitude = value;
            }

            /**
             * Gets the value of the longitude property.
             * 
             */
            public float getLongitude() {
                return longitude;
            }

            /**
             * Sets the value of the longitude property.
             * 
             */
            public void setLongitude(float value) {
                this.longitude = value;
            }

            /**
             * Gets the value of the magneticVariation property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getMagneticVariation() {
                return magneticVariation;
            }

            /**
             * Sets the value of the magneticVariation property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setMagneticVariation(Float value) {
                this.magneticVariation = value;
            }

        }

    }

}
