//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jeppesen.gs.otsas.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlightNumberTypeCommercialFlightNumber_QNAME = new QName("http://aeec.aviation-ia.net/633", "CommercialFlightNumber");
    private final static QName _CostIndexTypeValue_QNAME = new QName("http://aeec.aviation-ia.net/633", "Value");
    private final static QName _CostIndexTypeCorrectedValue_QNAME = new QName("http://aeec.aviation-ia.net/633", "CorrectedValue");
    private final static QName _AirportIdentificationTypeAirportIATACode_QNAME = new QName("http://aeec.aviation-ia.net/633", "AirportIATACode");
    private final static QName _AirportIdentificationTypeAirportICAOCode_QNAME = new QName("http://aeec.aviation-ia.net/633", "AirportICAOCode");
    private final static QName _FlightIdentificationTypeFlightNumber_QNAME = new QName("http://aeec.aviation-ia.net/633", "FlightNumber");
    private final static QName _FlightIdentificationTypeFlightIdentifier_QNAME = new QName("http://aeec.aviation-ia.net/633", "FlightIdentifier");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jeppesen.gs.otsas.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganizedTracks }
     * 
     */
    public OrganizedTracks createOrganizedTracks() {
        return new OrganizedTracks();
    }

    /**
     * Create an instance of {@link FlowType }
     * 
     */
    public FlowType createFlowType() {
        return new FlowType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link RemarksType }
     * 
     */
    public RemarksType createRemarksType() {
        return new RemarksType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link ObservationDetailsType }
     * 
     */
    public ObservationDetailsType createObservationDetailsType() {
        return new ObservationDetailsType();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.SupplementaryInformation }
     * 
     */
    public ObservationDetailsType.SupplementaryInformation createObservationDetailsTypeSupplementaryInformation() {
        return new ObservationDetailsType.SupplementaryInformation();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.Pressures }
     * 
     */
    public ObservationDetailsType.Pressures createObservationDetailsTypePressures() {
        return new ObservationDetailsType.Pressures();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.RunwayVisualRanges }
     * 
     */
    public ObservationDetailsType.RunwayVisualRanges createObservationDetailsTypeRunwayVisualRanges() {
        return new ObservationDetailsType.RunwayVisualRanges();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange }
     * 
     */
    public ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange createObservationDetailsTypeRunwayVisualRangesRunwayVisualRange() {
        return new ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities }
     * 
     */
    public ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities createObservationDetailsTypeRunwayVisualRangesRunwayVisualRangeVisibilities() {
        return new ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities();
    }

    /**
     * Create an instance of {@link DistanceType }
     * 
     */
    public DistanceType createDistanceType() {
        return new DistanceType();
    }

    /**
     * Create an instance of {@link DurationType }
     * 
     */
    public DurationType createDurationType() {
        return new DurationType();
    }

    /**
     * Create an instance of {@link ConnectionInfoType }
     * 
     */
    public ConnectionInfoType createConnectionInfoType() {
        return new ConnectionInfoType();
    }

    /**
     * Create an instance of {@link DensityType }
     * 
     */
    public DensityType createDensityType() {
        return new DensityType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link CloudsType }
     * 
     */
    public CloudsType createCloudsType() {
        return new CloudsType();
    }

    /**
     * Create an instance of {@link CloudsType.CloudDescriptions }
     * 
     */
    public CloudsType.CloudDescriptions createCloudsTypeCloudDescriptions() {
        return new CloudsType.CloudDescriptions();
    }

    /**
     * Create an instance of {@link GeographyType }
     * 
     */
    public GeographyType createGeographyType() {
        return new GeographyType();
    }

    /**
     * Create an instance of {@link GeographyType.Spot }
     * 
     */
    public GeographyType.Spot createGeographyTypeSpot() {
        return new GeographyType.Spot();
    }

    /**
     * Create an instance of {@link GeographyType.Polygon }
     * 
     */
    public GeographyType.Polygon createGeographyTypePolygon() {
        return new GeographyType.Polygon();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link AircraftType }
     * 
     */
    public AircraftType createAircraftType() {
        return new AircraftType();
    }

    /**
     * Create an instance of {@link VisibilitiesAndWeatherType }
     * 
     */
    public VisibilitiesAndWeatherType createVisibilitiesAndWeatherType() {
        return new VisibilitiesAndWeatherType();
    }

    /**
     * Create an instance of {@link VisibilityType }
     * 
     */
    public VisibilityType createVisibilityType() {
        return new VisibilityType();
    }

    /**
     * Create an instance of {@link RouteDefinitionType }
     * 
     */
    public RouteDefinitionType createRouteDefinitionType() {
        return new RouteDefinitionType();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.VerticalRoute }
     * 
     */
    public RouteDefinitionType.VerticalRoute createRouteDefinitionTypeVerticalRoute() {
        return new RouteDefinitionType.VerticalRoute();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute }
     * 
     */
    public RouteDefinitionType.LateralRoute createRouteDefinitionTypeLateralRoute() {
        return new RouteDefinitionType.LateralRoute();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute.RouteWaypoints }
     * 
     */
    public RouteDefinitionType.LateralRoute.RouteWaypoints createRouteDefinitionTypeLateralRouteRouteWaypoints() {
        return new RouteDefinitionType.LateralRoute.RouteWaypoints();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint }
     * 
     */
    public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint createRouteDefinitionTypeLateralRouteRouteWaypointsRouteWaypoint() {
        return new RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint();
    }

    /**
     * Create an instance of {@link DirectionType }
     * 
     */
    public DirectionType createDirectionType() {
        return new DirectionType();
    }

    /**
     * Create an instance of {@link CostIndexType }
     * 
     */
    public CostIndexType createCostIndexType() {
        return new CostIndexType();
    }

    /**
     * Create an instance of {@link AltitudeType }
     * 
     */
    public AltitudeType createAltitudeType() {
        return new AltitudeType();
    }

    /**
     * Create an instance of {@link SurfaceWindType }
     * 
     */
    public SurfaceWindType createSurfaceWindType() {
        return new SurfaceWindType();
    }

    /**
     * Create an instance of {@link SurfaceWindType.Directions }
     * 
     */
    public SurfaceWindType.Directions createSurfaceWindTypeDirections() {
        return new SurfaceWindType.Directions();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link SpeedType }
     * 
     */
    public SpeedType createSpeedType() {
        return new SpeedType();
    }

    /**
     * Create an instance of {@link WeightType }
     * 
     */
    public WeightType createWeightType() {
        return new WeightType();
    }

    /**
     * Create an instance of {@link OrganizedTracks.OrganizedTrackMessage }
     * 
     */
    public OrganizedTracks.OrganizedTrackMessage createOrganizedTracksOrganizedTrackMessage() {
        return new OrganizedTracks.OrganizedTrackMessage();
    }

    /**
     * Create an instance of {@link OrganizedTracks.OrganizedTracksSet }
     * 
     */
    public OrganizedTracks.OrganizedTracksSet createOrganizedTracksOrganizedTracksSet() {
        return new OrganizedTracks.OrganizedTracksSet();
    }

    /**
     * Create an instance of {@link OrganizedTracks.Remarks }
     * 
     */
    public OrganizedTracks.Remarks createOrganizedTracksRemarks() {
        return new OrganizedTracks.Remarks();
    }

    /**
     * Create an instance of {@link FlightType }
     * 
     */
    public FlightType createFlightType() {
        return new FlightType();
    }

    /**
     * Create an instance of {@link GeneralErrorType }
     * 
     */
    public GeneralErrorType createGeneralErrorType() {
        return new GeneralErrorType();
    }

    /**
     * Create an instance of {@link WeatherChangeType }
     * 
     */
    public WeatherChangeType createWeatherChangeType() {
        return new WeatherChangeType();
    }

    /**
     * Create an instance of {@link PersonalInfoType }
     * 
     */
    public PersonalInfoType createPersonalInfoType() {
        return new PersonalInfoType();
    }

    /**
     * Create an instance of {@link FlightNumberType }
     * 
     */
    public FlightNumberType createFlightNumberType() {
        return new FlightNumberType();
    }

    /**
     * Create an instance of {@link AirportFullIdentificationType }
     * 
     */
    public AirportFullIdentificationType createAirportFullIdentificationType() {
        return new AirportFullIdentificationType();
    }

    /**
     * Create an instance of {@link TimeBasicType }
     * 
     */
    public TimeBasicType createTimeBasicType() {
        return new TimeBasicType();
    }

    /**
     * Create an instance of {@link AirportIdentificationType }
     * 
     */
    public AirportIdentificationType createAirportIdentificationType() {
        return new AirportIdentificationType();
    }

    /**
     * Create an instance of {@link FlightIdentificationType }
     * 
     */
    public FlightIdentificationType createFlightIdentificationType() {
        return new FlightIdentificationType();
    }

    /**
     * Create an instance of {@link WindType }
     * 
     */
    public WindType createWindType() {
        return new WindType();
    }

    /**
     * Create an instance of {@link WeatherType }
     * 
     */
    public WeatherType createWeatherType() {
        return new WeatherType();
    }

    /**
     * Create an instance of {@link TravelDocumentType }
     * 
     */
    public TravelDocumentType createTravelDocumentType() {
        return new TravelDocumentType();
    }

    /**
     * Create an instance of {@link AltitudeInfoType }
     * 
     */
    public AltitudeInfoType createAltitudeInfoType() {
        return new AltitudeInfoType();
    }

    /**
     * Create an instance of {@link MachNumberType }
     * 
     */
    public MachNumberType createMachNumberType() {
        return new MachNumberType();
    }

    /**
     * Create an instance of {@link FlowType.Value }
     * 
     */
    public FlowType.Value createFlowTypeValue() {
        return new FlowType.Value();
    }

    /**
     * Create an instance of {@link FlowType.CorrectedValue }
     * 
     */
    public FlowType.CorrectedValue createFlowTypeCorrectedValue() {
        return new FlowType.CorrectedValue();
    }

    /**
     * Create an instance of {@link TemperatureType.Value }
     * 
     */
    public TemperatureType.Value createTemperatureTypeValue() {
        return new TemperatureType.Value();
    }

    /**
     * Create an instance of {@link TemperatureType.CorrectedValue }
     * 
     */
    public TemperatureType.CorrectedValue createTemperatureTypeCorrectedValue() {
        return new TemperatureType.CorrectedValue();
    }

    /**
     * Create an instance of {@link RemarksType.Remark }
     * 
     */
    public RemarksType.Remark createRemarksTypeRemark() {
        return new RemarksType.Remark();
    }

    /**
     * Create an instance of {@link TextType.Paragraph }
     * 
     */
    public TextType.Paragraph createTextTypeParagraph() {
        return new TextType.Paragraph();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.SurfaceWinds }
     * 
     */
    public ObservationDetailsType.SurfaceWinds createObservationDetailsTypeSurfaceWinds() {
        return new ObservationDetailsType.SurfaceWinds();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.Temperatures }
     * 
     */
    public ObservationDetailsType.Temperatures createObservationDetailsTypeTemperatures() {
        return new ObservationDetailsType.Temperatures();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.SupplementaryInformation.RecentWeather }
     * 
     */
    public ObservationDetailsType.SupplementaryInformation.RecentWeather createObservationDetailsTypeSupplementaryInformationRecentWeather() {
        return new ObservationDetailsType.SupplementaryInformation.RecentWeather();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.SupplementaryInformation.WindShear }
     * 
     */
    public ObservationDetailsType.SupplementaryInformation.WindShear createObservationDetailsTypeSupplementaryInformationWindShear() {
        return new ObservationDetailsType.SupplementaryInformation.WindShear();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.Pressures.QNH }
     * 
     */
    public ObservationDetailsType.Pressures.QNH createObservationDetailsTypePressuresQNH() {
        return new ObservationDetailsType.Pressures.QNH();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.Pressures.QFE }
     * 
     */
    public ObservationDetailsType.Pressures.QFE createObservationDetailsTypePressuresQFE() {
        return new ObservationDetailsType.Pressures.QFE();
    }

    /**
     * Create an instance of {@link PressureType.Value }
     * 
     */
    public PressureType.Value createPressureTypeValue() {
        return new PressureType.Value();
    }

    /**
     * Create an instance of {@link PressureType.CorrectedValue }
     * 
     */
    public PressureType.CorrectedValue createPressureTypeCorrectedValue() {
        return new PressureType.CorrectedValue();
    }

    /**
     * Create an instance of {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility }
     * 
     */
    public ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility createObservationDetailsTypeRunwayVisualRangesRunwayVisualRangeVisibilitiesVisibility() {
        return new ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility();
    }

    /**
     * Create an instance of {@link DistanceType.Value }
     * 
     */
    public DistanceType.Value createDistanceTypeValue() {
        return new DistanceType.Value();
    }

    /**
     * Create an instance of {@link DistanceType.CorrectedValue }
     * 
     */
    public DistanceType.CorrectedValue createDistanceTypeCorrectedValue() {
        return new DistanceType.CorrectedValue();
    }

    /**
     * Create an instance of {@link DurationType.CorrectedValue }
     * 
     */
    public DurationType.CorrectedValue createDurationTypeCorrectedValue() {
        return new DurationType.CorrectedValue();
    }

    /**
     * Create an instance of {@link ConnectionInfoType.IncomingFlights }
     * 
     */
    public ConnectionInfoType.IncomingFlights createConnectionInfoTypeIncomingFlights() {
        return new ConnectionInfoType.IncomingFlights();
    }

    /**
     * Create an instance of {@link ConnectionInfoType.OutgoingFlights }
     * 
     */
    public ConnectionInfoType.OutgoingFlights createConnectionInfoTypeOutgoingFlights() {
        return new ConnectionInfoType.OutgoingFlights();
    }

    /**
     * Create an instance of {@link DensityType.Value }
     * 
     */
    public DensityType.Value createDensityTypeValue() {
        return new DensityType.Value();
    }

    /**
     * Create an instance of {@link DensityType.CorrectedValue }
     * 
     */
    public DensityType.CorrectedValue createDensityTypeCorrectedValue() {
        return new DensityType.CorrectedValue();
    }

    /**
     * Create an instance of {@link VolumeType.Value }
     * 
     */
    public VolumeType.Value createVolumeTypeValue() {
        return new VolumeType.Value();
    }

    /**
     * Create an instance of {@link VolumeType.CorrectedValue }
     * 
     */
    public VolumeType.CorrectedValue createVolumeTypeCorrectedValue() {
        return new VolumeType.CorrectedValue();
    }

    /**
     * Create an instance of {@link TimeType.CorrectedValue }
     * 
     */
    public TimeType.CorrectedValue createTimeTypeCorrectedValue() {
        return new TimeType.CorrectedValue();
    }

    /**
     * Create an instance of {@link CloudsType.CloudDescriptions.CloudDescription }
     * 
     */
    public CloudsType.CloudDescriptions.CloudDescription createCloudsTypeCloudDescriptionsCloudDescription() {
        return new CloudsType.CloudDescriptions.CloudDescription();
    }

    /**
     * Create an instance of {@link GeographyType.Spot.Coordinates }
     * 
     */
    public GeographyType.Spot.Coordinates createGeographyTypeSpotCoordinates() {
        return new GeographyType.Spot.Coordinates();
    }

    /**
     * Create an instance of {@link GeographyType.Polygon.Coordinates }
     * 
     */
    public GeographyType.Polygon.Coordinates createGeographyTypePolygonCoordinates() {
        return new GeographyType.Polygon.Coordinates();
    }

    /**
     * Create an instance of {@link ContactInfoType.Address }
     * 
     */
    public ContactInfoType.Address createContactInfoTypeAddress() {
        return new ContactInfoType.Address();
    }

    /**
     * Create an instance of {@link AircraftType.AircraftModel }
     * 
     */
    public AircraftType.AircraftModel createAircraftTypeAircraftModel() {
        return new AircraftType.AircraftModel();
    }

    /**
     * Create an instance of {@link VisibilitiesAndWeatherType.Weather }
     * 
     */
    public VisibilitiesAndWeatherType.Weather createVisibilitiesAndWeatherTypeWeather() {
        return new VisibilitiesAndWeatherType.Weather();
    }

    /**
     * Create an instance of {@link VisibilityType.MinimumVisibility }
     * 
     */
    public VisibilityType.MinimumVisibility createVisibilityTypeMinimumVisibility() {
        return new VisibilityType.MinimumVisibility();
    }

    /**
     * Create an instance of {@link VisibilityType.MaximumVisibility }
     * 
     */
    public VisibilityType.MaximumVisibility createVisibilityTypeMaximumVisibility() {
        return new VisibilityType.MaximumVisibility();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.Airports }
     * 
     */
    public RouteDefinitionType.Airports createRouteDefinitionTypeAirports() {
        return new RouteDefinitionType.Airports();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.EntryConnections }
     * 
     */
    public RouteDefinitionType.EntryConnections createRouteDefinitionTypeEntryConnections() {
        return new RouteDefinitionType.EntryConnections();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.ExitConnections }
     * 
     */
    public RouteDefinitionType.ExitConnections createRouteDefinitionTypeExitConnections() {
        return new RouteDefinitionType.ExitConnections();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.Remarks }
     * 
     */
    public RouteDefinitionType.Remarks createRouteDefinitionTypeRemarks() {
        return new RouteDefinitionType.Remarks();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.VerticalRoute.Altitudes }
     * 
     */
    public RouteDefinitionType.VerticalRoute.Altitudes createRouteDefinitionTypeVerticalRouteAltitudes() {
        return new RouteDefinitionType.VerticalRoute.Altitudes();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates }
     * 
     */
    public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates createRouteDefinitionTypeLateralRouteRouteWaypointsRouteWaypointCoordinates() {
        return new RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway }
     * 
     */
    public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway createRouteDefinitionTypeLateralRouteRouteWaypointsRouteWaypointAirway() {
        return new RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway();
    }

    /**
     * Create an instance of {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions }
     * 
     */
    public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions createRouteDefinitionTypeLateralRouteRouteWaypointsRouteWaypointFunctions() {
        return new RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions();
    }

    /**
     * Create an instance of {@link DirectionType.Value }
     * 
     */
    public DirectionType.Value createDirectionTypeValue() {
        return new DirectionType.Value();
    }

    /**
     * Create an instance of {@link DirectionType.CorrectedValue }
     * 
     */
    public DirectionType.CorrectedValue createDirectionTypeCorrectedValue() {
        return new DirectionType.CorrectedValue();
    }

    /**
     * Create an instance of {@link CostIndexType.Value }
     * 
     */
    public CostIndexType.Value createCostIndexTypeValue() {
        return new CostIndexType.Value();
    }

    /**
     * Create an instance of {@link AltitudeType.Value }
     * 
     */
    public AltitudeType.Value createAltitudeTypeValue() {
        return new AltitudeType.Value();
    }

    /**
     * Create an instance of {@link AltitudeType.CorrectedValue }
     * 
     */
    public AltitudeType.CorrectedValue createAltitudeTypeCorrectedValue() {
        return new AltitudeType.CorrectedValue();
    }

    /**
     * Create an instance of {@link SurfaceWindType.Speeds }
     * 
     */
    public SurfaceWindType.Speeds createSurfaceWindTypeSpeeds() {
        return new SurfaceWindType.Speeds();
    }

    /**
     * Create an instance of {@link SurfaceWindType.Directions.VariableWindRange }
     * 
     */
    public SurfaceWindType.Directions.VariableWindRange createSurfaceWindTypeDirectionsVariableWindRange() {
        return new SurfaceWindType.Directions.VariableWindRange();
    }

    /**
     * Create an instance of {@link PersonType.Languages }
     * 
     */
    public PersonType.Languages createPersonTypeLanguages() {
        return new PersonType.Languages();
    }

    /**
     * Create an instance of {@link SpeedType.Value }
     * 
     */
    public SpeedType.Value createSpeedTypeValue() {
        return new SpeedType.Value();
    }

    /**
     * Create an instance of {@link SpeedType.CorrectedValue }
     * 
     */
    public SpeedType.CorrectedValue createSpeedTypeCorrectedValue() {
        return new SpeedType.CorrectedValue();
    }

    /**
     * Create an instance of {@link WeightType.Value }
     * 
     */
    public WeightType.Value createWeightTypeValue() {
        return new WeightType.Value();
    }

    /**
     * Create an instance of {@link WeightType.CorrectedValue }
     * 
     */
    public WeightType.CorrectedValue createWeightTypeCorrectedValue() {
        return new WeightType.CorrectedValue();
    }

    /**
     * Create an instance of {@link OrganizedTracks.OrganizedTrackMessage.NOTAMReference }
     * 
     */
    public OrganizedTracks.OrganizedTrackMessage.NOTAMReference createOrganizedTracksOrganizedTrackMessageNOTAMReference() {
        return new OrganizedTracks.OrganizedTrackMessage.NOTAMReference();
    }

    /**
     * Create an instance of {@link OrganizedTracks.OrganizedTracksSet.OrganizedTrack }
     * 
     */
    public OrganizedTracks.OrganizedTracksSet.OrganizedTrack createOrganizedTracksOrganizedTracksSetOrganizedTrack() {
        return new OrganizedTracks.OrganizedTracksSet.OrganizedTrack();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CommercialFlightNumber", scope = FlightNumberType.class)
    public JAXBElement<String> createFlightNumberTypeCommercialFlightNumber(String value) {
        return new JAXBElement<String>(_FlightNumberTypeCommercialFlightNumber_QNAME, String.class, FlightNumberType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CostIndexType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = CostIndexType.class)
    public JAXBElement<CostIndexType.Value> createCostIndexTypeValue(CostIndexType.Value value) {
        return new JAXBElement<CostIndexType.Value>(_CostIndexTypeValue_QNAME, CostIndexType.Value.class, CostIndexType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = CostIndexType.class)
    public JAXBElement<Integer> createCostIndexTypeCorrectedValue(Integer value) {
        return new JAXBElement<Integer>(_CostIndexTypeCorrectedValue_QNAME, Integer.class, CostIndexType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemperatureType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = TemperatureType.class)
    public JAXBElement<TemperatureType.Value> createTemperatureTypeValue(TemperatureType.Value value) {
        return new JAXBElement<TemperatureType.Value>(_CostIndexTypeValue_QNAME, TemperatureType.Value.class, TemperatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TemperatureType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = TemperatureType.class)
    public JAXBElement<TemperatureType.CorrectedValue> createTemperatureTypeCorrectedValue(TemperatureType.CorrectedValue value) {
        return new JAXBElement<TemperatureType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, TemperatureType.CorrectedValue.class, TemperatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistanceType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = DistanceType.class)
    public JAXBElement<DistanceType.Value> createDistanceTypeValue(DistanceType.Value value) {
        return new JAXBElement<DistanceType.Value>(_CostIndexTypeValue_QNAME, DistanceType.Value.class, DistanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistanceType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = DistanceType.class)
    public JAXBElement<DistanceType.CorrectedValue> createDistanceTypeCorrectedValue(DistanceType.CorrectedValue value) {
        return new JAXBElement<DistanceType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, DistanceType.CorrectedValue.class, DistanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlowType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = FlowType.class)
    public JAXBElement<FlowType.Value> createFlowTypeValue(FlowType.Value value) {
        return new JAXBElement<FlowType.Value>(_CostIndexTypeValue_QNAME, FlowType.Value.class, FlowType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlowType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = FlowType.class)
    public JAXBElement<FlowType.CorrectedValue> createFlowTypeCorrectedValue(FlowType.CorrectedValue value) {
        return new JAXBElement<FlowType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, FlowType.CorrectedValue.class, FlowType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = TimeType.class)
    public JAXBElement<XMLGregorianCalendar> createTimeTypeValue(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CostIndexTypeValue_QNAME, XMLGregorianCalendar.class, TimeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = TimeType.class)
    public JAXBElement<TimeType.CorrectedValue> createTimeTypeCorrectedValue(TimeType.CorrectedValue value) {
        return new JAXBElement<TimeType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, TimeType.CorrectedValue.class, TimeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = DurationType.class)
    public JAXBElement<Duration> createDurationTypeValue(Duration value) {
        return new JAXBElement<Duration>(_CostIndexTypeValue_QNAME, Duration.class, DurationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DurationType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = DurationType.class)
    public JAXBElement<DurationType.CorrectedValue> createDurationTypeCorrectedValue(DurationType.CorrectedValue value) {
        return new JAXBElement<DurationType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, DurationType.CorrectedValue.class, DurationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectionType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = DirectionType.class)
    public JAXBElement<DirectionType.Value> createDirectionTypeValue(DirectionType.Value value) {
        return new JAXBElement<DirectionType.Value>(_CostIndexTypeValue_QNAME, DirectionType.Value.class, DirectionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectionType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = DirectionType.class)
    public JAXBElement<DirectionType.CorrectedValue> createDirectionTypeCorrectedValue(DirectionType.CorrectedValue value) {
        return new JAXBElement<DirectionType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, DirectionType.CorrectedValue.class, DirectionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AltitudeType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = AltitudeType.class)
    public JAXBElement<AltitudeType.Value> createAltitudeTypeValue(AltitudeType.Value value) {
        return new JAXBElement<AltitudeType.Value>(_CostIndexTypeValue_QNAME, AltitudeType.Value.class, AltitudeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AltitudeType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = AltitudeType.class)
    public JAXBElement<AltitudeType.CorrectedValue> createAltitudeTypeCorrectedValue(AltitudeType.CorrectedValue value) {
        return new JAXBElement<AltitudeType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, AltitudeType.CorrectedValue.class, AltitudeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "AirportIATACode", scope = AirportIdentificationType.class)
    public JAXBElement<String> createAirportIdentificationTypeAirportIATACode(String value) {
        return new JAXBElement<String>(_AirportIdentificationTypeAirportIATACode_QNAME, String.class, AirportIdentificationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "AirportICAOCode", scope = AirportIdentificationType.class)
    public JAXBElement<String> createAirportIdentificationTypeAirportICAOCode(String value) {
        return new JAXBElement<String>(_AirportIdentificationTypeAirportICAOCode_QNAME, String.class, AirportIdentificationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VolumeType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = VolumeType.class)
    public JAXBElement<VolumeType.Value> createVolumeTypeValue(VolumeType.Value value) {
        return new JAXBElement<VolumeType.Value>(_CostIndexTypeValue_QNAME, VolumeType.Value.class, VolumeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VolumeType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = VolumeType.class)
    public JAXBElement<VolumeType.CorrectedValue> createVolumeTypeCorrectedValue(VolumeType.CorrectedValue value) {
        return new JAXBElement<VolumeType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, VolumeType.CorrectedValue.class, VolumeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "AirportIATACode", scope = AirportFullIdentificationType.class)
    public JAXBElement<String> createAirportFullIdentificationTypeAirportIATACode(String value) {
        return new JAXBElement<String>(_AirportIdentificationTypeAirportIATACode_QNAME, String.class, AirportFullIdentificationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "AirportICAOCode", scope = AirportFullIdentificationType.class)
    public JAXBElement<String> createAirportFullIdentificationTypeAirportICAOCode(String value) {
        return new JAXBElement<String>(_AirportIdentificationTypeAirportICAOCode_QNAME, String.class, AirportFullIdentificationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = SpeedType.class)
    public JAXBElement<SpeedType.Value> createSpeedTypeValue(SpeedType.Value value) {
        return new JAXBElement<SpeedType.Value>(_CostIndexTypeValue_QNAME, SpeedType.Value.class, SpeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = SpeedType.class)
    public JAXBElement<SpeedType.CorrectedValue> createSpeedTypeCorrectedValue(SpeedType.CorrectedValue value) {
        return new JAXBElement<SpeedType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, SpeedType.CorrectedValue.class, SpeedType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = MachNumberType.class)
    public JAXBElement<BigDecimal> createMachNumberTypeValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CostIndexTypeValue_QNAME, BigDecimal.class, MachNumberType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = MachNumberType.class)
    public JAXBElement<BigDecimal> createMachNumberTypeCorrectedValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CostIndexTypeCorrectedValue_QNAME, BigDecimal.class, MachNumberType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeightType.Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "Value", scope = WeightType.class)
    public JAXBElement<WeightType.Value> createWeightTypeValue(WeightType.Value value) {
        return new JAXBElement<WeightType.Value>(_CostIndexTypeValue_QNAME, WeightType.Value.class, WeightType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeightType.CorrectedValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "CorrectedValue", scope = WeightType.class)
    public JAXBElement<WeightType.CorrectedValue> createWeightTypeCorrectedValue(WeightType.CorrectedValue value) {
        return new JAXBElement<WeightType.CorrectedValue>(_CostIndexTypeCorrectedValue_QNAME, WeightType.CorrectedValue.class, WeightType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlightNumberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "FlightNumber", scope = FlightIdentificationType.class)
    public JAXBElement<FlightNumberType> createFlightIdentificationTypeFlightNumber(FlightNumberType value) {
        return new JAXBElement<FlightNumberType>(_FlightIdentificationTypeFlightNumber_QNAME, FlightNumberType.class, FlightIdentificationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://aeec.aviation-ia.net/633", name = "FlightIdentifier", scope = FlightIdentificationType.class)
    public JAXBElement<String> createFlightIdentificationTypeFlightIdentifier(String value) {
        return new JAXBElement<String>(_FlightIdentificationTypeFlightIdentifier_QNAME, String.class, FlightIdentificationType.class, value);
    }

}
