//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ObservationDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservationDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SurfaceWinds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SurfaceWind" type="{http://aeec.aviation-ia.net/633}SurfaceWindType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VisibilitiesAndWeather" type="{http://aeec.aviation-ia.net/633}VisibilitiesAndWeatherType"/>
 *         &lt;element name="RunwayVisualRanges" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RunwayVisualRange" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Visibilities">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Visibility" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
 *                                               &lt;attribute name="runwaySection">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;enumeration value="THR"/>
 *                                                     &lt;enumeration value="MID"/>
 *                                                     &lt;enumeration value="END"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                               &lt;attribute name="aboveBelow">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;enumeration value="above"/>
 *                                                     &lt;enumeration value="below"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="runwayIdentifier" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="2"/>
 *                                 &lt;maxLength value="3"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="tendency">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="upward"/>
 *                                 &lt;enumeration value="downward"/>
 *                                 &lt;enumeration value="no distinct tendency"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Temperatures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AirTemperature" type="{http://aeec.aviation-ia.net/633}TemperatureType"/>
 *                   &lt;element name="DewPointTemperature" type="{http://aeec.aviation-ia.net/633}TemperatureType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pressures">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QNH" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
 *                           &lt;attribute name="runwayIdentifier">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="2"/>
 *                                 &lt;maxLength value="3"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="QFE" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
 *                           &lt;attribute name="runwayIdentifier">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="2"/>
 *                                 &lt;maxLength value="3"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SupplementaryInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RecentWeather" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://aeec.aviation-ia.net/633}WeatherType">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="WindShear" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="allRunway" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="runwayIdentifier">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="2"/>
 *                                 &lt;maxLength value="3"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;any namespace='##other' minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Trend" type="{http://aeec.aviation-ia.net/633}WeatherChangeType" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservationDetailsType", propOrder = {
    "surfaceWinds",
    "visibilitiesAndWeather",
    "runwayVisualRanges",
    "temperatures",
    "pressures",
    "supplementaryInformation",
    "trend",
    "any"
})
public class ObservationDetailsType {

    @XmlElement(name = "SurfaceWinds", required = true)
    protected ObservationDetailsType.SurfaceWinds surfaceWinds;
    @XmlElement(name = "VisibilitiesAndWeather", required = true)
    protected VisibilitiesAndWeatherType visibilitiesAndWeather;
    @XmlElement(name = "RunwayVisualRanges")
    protected ObservationDetailsType.RunwayVisualRanges runwayVisualRanges;
    @XmlElement(name = "Temperatures", required = true)
    protected ObservationDetailsType.Temperatures temperatures;
    @XmlElement(name = "Pressures", required = true)
    protected ObservationDetailsType.Pressures pressures;
    @XmlElement(name = "SupplementaryInformation")
    protected ObservationDetailsType.SupplementaryInformation supplementaryInformation;
    @XmlElement(name = "Trend")
    protected WeatherChangeType trend;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the surfaceWinds property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationDetailsType.SurfaceWinds }
     *     
     */
    public ObservationDetailsType.SurfaceWinds getSurfaceWinds() {
        return surfaceWinds;
    }

    /**
     * Sets the value of the surfaceWinds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationDetailsType.SurfaceWinds }
     *     
     */
    public void setSurfaceWinds(ObservationDetailsType.SurfaceWinds value) {
        this.surfaceWinds = value;
    }

    /**
     * Gets the value of the visibilitiesAndWeather property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilitiesAndWeatherType }
     *     
     */
    public VisibilitiesAndWeatherType getVisibilitiesAndWeather() {
        return visibilitiesAndWeather;
    }

    /**
     * Sets the value of the visibilitiesAndWeather property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilitiesAndWeatherType }
     *     
     */
    public void setVisibilitiesAndWeather(VisibilitiesAndWeatherType value) {
        this.visibilitiesAndWeather = value;
    }

    /**
     * Gets the value of the runwayVisualRanges property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationDetailsType.RunwayVisualRanges }
     *     
     */
    public ObservationDetailsType.RunwayVisualRanges getRunwayVisualRanges() {
        return runwayVisualRanges;
    }

    /**
     * Sets the value of the runwayVisualRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationDetailsType.RunwayVisualRanges }
     *     
     */
    public void setRunwayVisualRanges(ObservationDetailsType.RunwayVisualRanges value) {
        this.runwayVisualRanges = value;
    }

    /**
     * Gets the value of the temperatures property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationDetailsType.Temperatures }
     *     
     */
    public ObservationDetailsType.Temperatures getTemperatures() {
        return temperatures;
    }

    /**
     * Sets the value of the temperatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationDetailsType.Temperatures }
     *     
     */
    public void setTemperatures(ObservationDetailsType.Temperatures value) {
        this.temperatures = value;
    }

    /**
     * Gets the value of the pressures property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationDetailsType.Pressures }
     *     
     */
    public ObservationDetailsType.Pressures getPressures() {
        return pressures;
    }

    /**
     * Sets the value of the pressures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationDetailsType.Pressures }
     *     
     */
    public void setPressures(ObservationDetailsType.Pressures value) {
        this.pressures = value;
    }

    /**
     * Gets the value of the supplementaryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationDetailsType.SupplementaryInformation }
     *     
     */
    public ObservationDetailsType.SupplementaryInformation getSupplementaryInformation() {
        return supplementaryInformation;
    }

    /**
     * Sets the value of the supplementaryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationDetailsType.SupplementaryInformation }
     *     
     */
    public void setSupplementaryInformation(ObservationDetailsType.SupplementaryInformation value) {
        this.supplementaryInformation = value;
    }

    /**
     * Gets the value of the trend property.
     * 
     * @return
     *     possible object is
     *     {@link WeatherChangeType }
     *     
     */
    public WeatherChangeType getTrend() {
        return trend;
    }

    /**
     * Sets the value of the trend property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeatherChangeType }
     *     
     */
    public void setTrend(WeatherChangeType value) {
        this.trend = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QNH" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
     *                 &lt;attribute name="runwayIdentifier">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="2"/>
     *                       &lt;maxLength value="3"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="QFE" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
     *                 &lt;attribute name="runwayIdentifier">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="2"/>
     *                       &lt;maxLength value="3"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qnh",
        "qfe"
    })
    public static class Pressures {

        @XmlElement(name = "QNH", required = true)
        protected List<ObservationDetailsType.Pressures.QNH> qnh;
        @XmlElement(name = "QFE")
        protected List<ObservationDetailsType.Pressures.QFE> qfe;

        /**
         * Gets the value of the qnh property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qnh property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQNH().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationDetailsType.Pressures.QNH }
         * 
         * 
         */
        public List<ObservationDetailsType.Pressures.QNH> getQNH() {
            if (qnh == null) {
                qnh = new ArrayList<ObservationDetailsType.Pressures.QNH>();
            }
            return this.qnh;
        }

        /**
         * Gets the value of the qfe property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qfe property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQFE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationDetailsType.Pressures.QFE }
         * 
         * 
         */
        public List<ObservationDetailsType.Pressures.QFE> getQFE() {
            if (qfe == null) {
                qfe = new ArrayList<ObservationDetailsType.Pressures.QFE>();
            }
            return this.qfe;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
         *       &lt;attribute name="runwayIdentifier">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="2"/>
         *             &lt;maxLength value="3"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class QFE
            extends PressureType
        {

            @XmlAttribute(name = "runwayIdentifier")
            protected String runwayIdentifier;

            /**
             * Gets the value of the runwayIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunwayIdentifier() {
                return runwayIdentifier;
            }

            /**
             * Sets the value of the runwayIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunwayIdentifier(String value) {
                this.runwayIdentifier = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://aeec.aviation-ia.net/633}PressureType">
         *       &lt;attribute name="runwayIdentifier">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="2"/>
         *             &lt;maxLength value="3"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class QNH
            extends PressureType
        {

            @XmlAttribute(name = "runwayIdentifier")
            protected String runwayIdentifier;

            /**
             * Gets the value of the runwayIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunwayIdentifier() {
                return runwayIdentifier;
            }

            /**
             * Sets the value of the runwayIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunwayIdentifier(String value) {
                this.runwayIdentifier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RunwayVisualRange" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Visibilities">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Visibility" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
     *                                     &lt;attribute name="runwaySection">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;enumeration value="THR"/>
     *                                           &lt;enumeration value="MID"/>
     *                                           &lt;enumeration value="END"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                     &lt;attribute name="aboveBelow">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;enumeration value="above"/>
     *                                           &lt;enumeration value="below"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="runwayIdentifier" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="2"/>
     *                       &lt;maxLength value="3"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="tendency">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="upward"/>
     *                       &lt;enumeration value="downward"/>
     *                       &lt;enumeration value="no distinct tendency"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runwayVisualRange"
    })
    public static class RunwayVisualRanges {

        @XmlElement(name = "RunwayVisualRange", required = true)
        protected List<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange> runwayVisualRange;

        /**
         * Gets the value of the runwayVisualRange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runwayVisualRange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRunwayVisualRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange }
         * 
         * 
         */
        public List<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange> getRunwayVisualRange() {
            if (runwayVisualRange == null) {
                runwayVisualRange = new ArrayList<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange>();
            }
            return this.runwayVisualRange;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Visibilities">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Visibility" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
         *                           &lt;attribute name="runwaySection">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;enumeration value="THR"/>
         *                                 &lt;enumeration value="MID"/>
         *                                 &lt;enumeration value="END"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                           &lt;attribute name="aboveBelow">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;enumeration value="above"/>
         *                                 &lt;enumeration value="below"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="runwayIdentifier" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="2"/>
         *             &lt;maxLength value="3"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="tendency">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="upward"/>
         *             &lt;enumeration value="downward"/>
         *             &lt;enumeration value="no distinct tendency"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "visibilities"
        })
        public static class RunwayVisualRange {

            @XmlElement(name = "Visibilities", required = true)
            protected ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities visibilities;
            @XmlAttribute(name = "runwayIdentifier", required = true)
            protected String runwayIdentifier;
            @XmlAttribute(name = "tendency")
            protected String tendency;

            /**
             * Gets the value of the visibilities property.
             * 
             * @return
             *     possible object is
             *     {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities }
             *     
             */
            public ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities getVisibilities() {
                return visibilities;
            }

            /**
             * Sets the value of the visibilities property.
             * 
             * @param value
             *     allowed object is
             *     {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities }
             *     
             */
            public void setVisibilities(ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities value) {
                this.visibilities = value;
            }

            /**
             * Gets the value of the runwayIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunwayIdentifier() {
                return runwayIdentifier;
            }

            /**
             * Sets the value of the runwayIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunwayIdentifier(String value) {
                this.runwayIdentifier = value;
            }

            /**
             * Gets the value of the tendency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTendency() {
                return tendency;
            }

            /**
             * Sets the value of the tendency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTendency(String value) {
                this.tendency = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Visibility" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
             *                 &lt;attribute name="runwaySection">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;enumeration value="THR"/>
             *                       &lt;enumeration value="MID"/>
             *                       &lt;enumeration value="END"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *                 &lt;attribute name="aboveBelow">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;enumeration value="above"/>
             *                       &lt;enumeration value="below"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "visibility"
            })
            public static class Visibilities {

                @XmlElement(name = "Visibility", required = true)
                protected List<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility> visibility;

                /**
                 * Gets the value of the visibility property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the visibility property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getVisibility().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility }
                 * 
                 * 
                 */
                public List<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility> getVisibility() {
                    if (visibility == null) {
                        visibility = new ArrayList<ObservationDetailsType.RunwayVisualRanges.RunwayVisualRange.Visibilities.Visibility>();
                    }
                    return this.visibility;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
                 *       &lt;attribute name="runwaySection">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;enumeration value="THR"/>
                 *             &lt;enumeration value="MID"/>
                 *             &lt;enumeration value="END"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *       &lt;attribute name="aboveBelow">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;enumeration value="above"/>
                 *             &lt;enumeration value="below"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Visibility
                    extends DistanceType
                {

                    @XmlAttribute(name = "runwaySection")
                    protected String runwaySection;
                    @XmlAttribute(name = "aboveBelow")
                    protected String aboveBelow;

                    /**
                     * Gets the value of the runwaySection property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRunwaySection() {
                        return runwaySection;
                    }

                    /**
                     * Sets the value of the runwaySection property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRunwaySection(String value) {
                        this.runwaySection = value;
                    }

                    /**
                     * Gets the value of the aboveBelow property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAboveBelow() {
                        return aboveBelow;
                    }

                    /**
                     * Sets the value of the aboveBelow property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAboveBelow(String value) {
                        this.aboveBelow = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RecentWeather" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://aeec.aviation-ia.net/633}WeatherType">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="WindShear" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="allRunway" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="runwayIdentifier">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="2"/>
     *                       &lt;maxLength value="3"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;any namespace='##other' minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recentWeather",
        "windShear",
        "any"
    })
    public static class SupplementaryInformation {

        @XmlElement(name = "RecentWeather")
        protected List<ObservationDetailsType.SupplementaryInformation.RecentWeather> recentWeather;
        @XmlElement(name = "WindShear")
        protected List<ObservationDetailsType.SupplementaryInformation.WindShear> windShear;
        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the recentWeather property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recentWeather property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecentWeather().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationDetailsType.SupplementaryInformation.RecentWeather }
         * 
         * 
         */
        public List<ObservationDetailsType.SupplementaryInformation.RecentWeather> getRecentWeather() {
            if (recentWeather == null) {
                recentWeather = new ArrayList<ObservationDetailsType.SupplementaryInformation.RecentWeather>();
            }
            return this.recentWeather;
        }

        /**
         * Gets the value of the windShear property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the windShear property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWindShear().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObservationDetailsType.SupplementaryInformation.WindShear }
         * 
         * 
         */
        public List<ObservationDetailsType.SupplementaryInformation.WindShear> getWindShear() {
            if (windShear == null) {
                windShear = new ArrayList<ObservationDetailsType.SupplementaryInformation.WindShear>();
            }
            return this.windShear;
        }

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://aeec.aviation-ia.net/633}WeatherType">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RecentWeather
            extends WeatherType
        {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="allRunway" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="runwayIdentifier">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="2"/>
         *             &lt;maxLength value="3"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class WindShear {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "allRunway")
            protected Boolean allRunway;
            @XmlAttribute(name = "runwayIdentifier")
            protected String runwayIdentifier;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the allRunway property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAllRunway() {
                return allRunway;
            }

            /**
             * Sets the value of the allRunway property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAllRunway(Boolean value) {
                this.allRunway = value;
            }

            /**
             * Gets the value of the runwayIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRunwayIdentifier() {
                return runwayIdentifier;
            }

            /**
             * Sets the value of the runwayIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRunwayIdentifier(String value) {
                this.runwayIdentifier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SurfaceWind" type="{http://aeec.aviation-ia.net/633}SurfaceWindType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "surfaceWind"
    })
    public static class SurfaceWinds {

        @XmlElement(name = "SurfaceWind", required = true)
        protected List<SurfaceWindType> surfaceWind;

        /**
         * Gets the value of the surfaceWind property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the surfaceWind property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSurfaceWind().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SurfaceWindType }
         * 
         * 
         */
        public List<SurfaceWindType> getSurfaceWind() {
            if (surfaceWind == null) {
                surfaceWind = new ArrayList<SurfaceWindType>();
            }
            return this.surfaceWind;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AirTemperature" type="{http://aeec.aviation-ia.net/633}TemperatureType"/>
     *         &lt;element name="DewPointTemperature" type="{http://aeec.aviation-ia.net/633}TemperatureType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airTemperature",
        "dewPointTemperature"
    })
    public static class Temperatures {

        @XmlElement(name = "AirTemperature", required = true)
        protected TemperatureType airTemperature;
        @XmlElement(name = "DewPointTemperature", required = true)
        protected TemperatureType dewPointTemperature;

        /**
         * Gets the value of the airTemperature property.
         * 
         * @return
         *     possible object is
         *     {@link TemperatureType }
         *     
         */
        public TemperatureType getAirTemperature() {
            return airTemperature;
        }

        /**
         * Sets the value of the airTemperature property.
         * 
         * @param value
         *     allowed object is
         *     {@link TemperatureType }
         *     
         */
        public void setAirTemperature(TemperatureType value) {
            this.airTemperature = value;
        }

        /**
         * Gets the value of the dewPointTemperature property.
         * 
         * @return
         *     possible object is
         *     {@link TemperatureType }
         *     
         */
        public TemperatureType getDewPointTemperature() {
            return dewPointTemperature;
        }

        /**
         * Sets the value of the dewPointTemperature property.
         * 
         * @param value
         *     allowed object is
         *     {@link TemperatureType }
         *     
         */
        public void setDewPointTemperature(TemperatureType value) {
            this.dewPointTemperature = value;
        }

    }

}
