//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="OrganizedTracksSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OrganizedTrack" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://aeec.aviation-ia.net/633}RouteDefinitionType">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Remarks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Remark" type="{http://aeec.aviation-ia.net/633}TextType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OrganizedTrackMessage" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="NOTAMReference" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="issuer">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="0"/>
 *                                 &lt;maxLength value="32"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="series">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;length value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="serial" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="OrganizedTrackMessageText" type="{http://aeec.aviation-ia.net/633}TextType"/>
 *                   &lt;any namespace='##other'/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="trackMessageIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="area" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "OrganizedTracks")
public class OrganizedTracks {

    @XmlElement(name = "OrganizedTracksSet", required = true)
    protected OrganizedTracks.OrganizedTracksSet organizedTracksSet;
    @XmlElement(name = "Remarks")
    protected OrganizedTracks.Remarks remarks;
    @XmlElement(name = "OrganizedTrackMessage")
    protected OrganizedTracks.OrganizedTrackMessage organizedTrackMessage;
    @XmlAttribute(name = "trackMessageIdentifier")
    protected String trackMessageIdentifier;
    @XmlAttribute(name = "area")
    protected String area;

    /**
     * Gets the value of the organizedTracksSet property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizedTracks.OrganizedTracksSet }
     *     
     */
    public OrganizedTracks.OrganizedTracksSet getOrganizedTracksSet() {
        return organizedTracksSet;
    }

    /**
     * Sets the value of the organizedTracksSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizedTracks.OrganizedTracksSet }
     *     
     */
    public void setOrganizedTracksSet(OrganizedTracks.OrganizedTracksSet value) {
        this.organizedTracksSet = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizedTracks.Remarks }
     *     
     */
    public OrganizedTracks.Remarks getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizedTracks.Remarks }
     *     
     */
    public void setRemarks(OrganizedTracks.Remarks value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the organizedTrackMessage property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizedTracks.OrganizedTrackMessage }
     *     
     */
    public OrganizedTracks.OrganizedTrackMessage getOrganizedTrackMessage() {
        return organizedTrackMessage;
    }

    /**
     * Sets the value of the organizedTrackMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizedTracks.OrganizedTrackMessage }
     *     
     */
    public void setOrganizedTrackMessage(OrganizedTracks.OrganizedTrackMessage value) {
        this.organizedTrackMessage = value;
    }

    /**
     * Gets the value of the trackMessageIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackMessageIdentifier() {
        return trackMessageIdentifier;
    }

    /**
     * Sets the value of the trackMessageIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackMessageIdentifier(String value) {
        this.trackMessageIdentifier = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArea(String value) {
        this.area = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="NOTAMReference" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="issuer">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="0"/>
     *                       &lt;maxLength value="32"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="series">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;length value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="serial" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="OrganizedTrackMessageText" type="{http://aeec.aviation-ia.net/633}TextType"/>
     *         &lt;any namespace='##other'/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notamReference",
        "organizedTrackMessageText",
        "any"
    })
    public static class OrganizedTrackMessage {

        @XmlElement(name = "NOTAMReference")
        protected OrganizedTracks.OrganizedTrackMessage.NOTAMReference notamReference;
        @XmlElement(name = "OrganizedTrackMessageText")
        protected TextType organizedTrackMessageText;
        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the notamReference property.
         * 
         * @return
         *     possible object is
         *     {@link OrganizedTracks.OrganizedTrackMessage.NOTAMReference }
         *     
         */
        public OrganizedTracks.OrganizedTrackMessage.NOTAMReference getNOTAMReference() {
            return notamReference;
        }

        /**
         * Sets the value of the notamReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link OrganizedTracks.OrganizedTrackMessage.NOTAMReference }
         *     
         */
        public void setNOTAMReference(OrganizedTracks.OrganizedTrackMessage.NOTAMReference value) {
            this.notamReference = value;
        }

        /**
         * Gets the value of the organizedTrackMessageText property.
         * 
         * @return
         *     possible object is
         *     {@link TextType }
         *     
         */
        public TextType getOrganizedTrackMessageText() {
            return organizedTrackMessageText;
        }

        /**
         * Sets the value of the organizedTrackMessageText property.
         * 
         * @param value
         *     allowed object is
         *     {@link TextType }
         *     
         */
        public void setOrganizedTrackMessageText(TextType value) {
            this.organizedTrackMessageText = value;
        }

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="issuer">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="0"/>
         *             &lt;maxLength value="32"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="series">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;length value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="serial" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="year" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class NOTAMReference {

            @XmlAttribute(name = "issuer")
            protected String issuer;
            @XmlAttribute(name = "series")
            protected String series;
            @XmlAttribute(name = "serial", required = true)
            protected String serial;
            @XmlAttribute(name = "year")
            protected Integer year;

            /**
             * Gets the value of the issuer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIssuer() {
                return issuer;
            }

            /**
             * Sets the value of the issuer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIssuer(String value) {
                this.issuer = value;
            }

            /**
             * Gets the value of the series property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeries() {
                return series;
            }

            /**
             * Sets the value of the series property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeries(String value) {
                this.series = value;
            }

            /**
             * Gets the value of the serial property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSerial() {
                return serial;
            }

            /**
             * Sets the value of the serial property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSerial(String value) {
                this.serial = value;
            }

            /**
             * Gets the value of the year property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setYear(Integer value) {
                this.year = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OrganizedTrack" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://aeec.aviation-ia.net/633}RouteDefinitionType">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organizedTrack"
    })
    public static class OrganizedTracksSet {

        @XmlElement(name = "OrganizedTrack", required = true)
        protected List<OrganizedTracks.OrganizedTracksSet.OrganizedTrack> organizedTrack;

        /**
         * Gets the value of the organizedTrack property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the organizedTrack property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrganizedTrack().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrganizedTracks.OrganizedTracksSet.OrganizedTrack }
         * 
         * 
         */
        public List<OrganizedTracks.OrganizedTracksSet.OrganizedTrack> getOrganizedTrack() {
            if (organizedTrack == null) {
                organizedTrack = new ArrayList<OrganizedTracks.OrganizedTracksSet.OrganizedTrack>();
            }
            return this.organizedTrack;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://aeec.aviation-ia.net/633}RouteDefinitionType">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OrganizedTrack
            extends RouteDefinitionType
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Remark" type="{http://aeec.aviation-ia.net/633}TextType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "remark"
    })
    public static class Remarks {

        @XmlElement(name = "Remark", required = true)
        protected List<TextType> remark;

        /**
         * Gets the value of the remark property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the remark property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRemark().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextType }
         * 
         * 
         */
        public List<TextType> getRemark() {
            if (remark == null) {
                remark = new ArrayList<TextType>();
            }
            return this.remark;
        }

    }

}
