//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PossibleOperationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PossibleOperationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CPDLC"/>
 *     &lt;enumeration value="ERA"/>
 *     &lt;enumeration value="ETOPS"/>
 *     &lt;enumeration value="MNPS"/>
 *     &lt;enumeration value="RVSM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PossibleOperationType")
@XmlEnum
public enum PossibleOperationType {

    CPDLC,
    ERA,
    ETOPS,
    MNPS,
    RVSM;

    public String value() {
        return name();
    }

    public static PossibleOperationType fromValue(String v) {
        return valueOf(v);
    }

}
