//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcedureType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcedureType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Economic"/>
 *     &lt;enumeration value="LongRangeCruise"/>
 *     &lt;enumeration value="LongRangeTurboprop"/>
 *     &lt;enumeration value="MaximumSpeed"/>
 *     &lt;enumeration value="MaximumEnduranceCruise"/>
 *     &lt;enumeration value="MaximumRangeCruise"/>
 *     &lt;enumeration value="RecommendedTurboprop"/>
 *     &lt;enumeration value="RecommendedCruisePower"/>
 *     &lt;enumeration value="Speed"/>
 *     &lt;enumeration value="Variable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcedureType")
@XmlEnum
public enum ProcedureType {

    @XmlEnumValue("Economic")
    ECONOMIC("Economic"),
    @XmlEnumValue("LongRangeCruise")
    LONG_RANGE_CRUISE("LongRangeCruise"),
    @XmlEnumValue("LongRangeTurboprop")
    LONG_RANGE_TURBOPROP("LongRangeTurboprop"),
    @XmlEnumValue("MaximumSpeed")
    MAXIMUM_SPEED("MaximumSpeed"),
    @XmlEnumValue("MaximumEnduranceCruise")
    MAXIMUM_ENDURANCE_CRUISE("MaximumEnduranceCruise"),
    @XmlEnumValue("MaximumRangeCruise")
    MAXIMUM_RANGE_CRUISE("MaximumRangeCruise"),
    @XmlEnumValue("RecommendedTurboprop")
    RECOMMENDED_TURBOPROP("RecommendedTurboprop"),
    @XmlEnumValue("RecommendedCruisePower")
    RECOMMENDED_CRUISE_POWER("RecommendedCruisePower"),
    @XmlEnumValue("Speed")
    SPEED("Speed"),
    @XmlEnumValue("Variable")
    VARIABLE("Variable");
    private final String value;

    ProcedureType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcedureType fromValue(String v) {
        for (ProcedureType c: ProcedureType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
