//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RankType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RankType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Captain"/>
 *     &lt;enumeration value="SeniorFirstOfficer"/>
 *     &lt;enumeration value="FirstOfficer"/>
 *     &lt;enumeration value="SecondOfficer"/>
 *     &lt;enumeration value="ThirdOfficer"/>
 *     &lt;enumeration value="FlightEngineer"/>
 *     &lt;enumeration value="SeniorPurser"/>
 *     &lt;enumeration value="Purser"/>
 *     &lt;enumeration value="SeniorCrewMember"/>
 *     &lt;enumeration value="FirstClassAttendant"/>
 *     &lt;enumeration value="BusinessClassAttendant"/>
 *     &lt;enumeration value="CabinAttendant"/>
 *     &lt;enumeration value="LocalCrew"/>
 *     &lt;enumeration value="Trainee"/>
 *     &lt;enumeration value="Observer"/>
 *     &lt;enumeration value="GroundEngineer"/>
 *     &lt;enumeration value="AnimalAttendant"/>
 *     &lt;enumeration value="SecurityOfficer"/>
 *     &lt;enumeration value="AuthorityInspector"/>
 *     &lt;enumeration value="Loadmaster"/>
 *     &lt;enumeration value="Doctor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RankType")
@XmlEnum
public enum RankType {

    @XmlEnumValue("Captain")
    CAPTAIN("Captain"),
    @XmlEnumValue("SeniorFirstOfficer")
    SENIOR_FIRST_OFFICER("SeniorFirstOfficer"),
    @XmlEnumValue("FirstOfficer")
    FIRST_OFFICER("FirstOfficer"),
    @XmlEnumValue("SecondOfficer")
    SECOND_OFFICER("SecondOfficer"),
    @XmlEnumValue("ThirdOfficer")
    THIRD_OFFICER("ThirdOfficer"),
    @XmlEnumValue("FlightEngineer")
    FLIGHT_ENGINEER("FlightEngineer"),
    @XmlEnumValue("SeniorPurser")
    SENIOR_PURSER("SeniorPurser"),
    @XmlEnumValue("Purser")
    PURSER("Purser"),
    @XmlEnumValue("SeniorCrewMember")
    SENIOR_CREW_MEMBER("SeniorCrewMember"),
    @XmlEnumValue("FirstClassAttendant")
    FIRST_CLASS_ATTENDANT("FirstClassAttendant"),
    @XmlEnumValue("BusinessClassAttendant")
    BUSINESS_CLASS_ATTENDANT("BusinessClassAttendant"),
    @XmlEnumValue("CabinAttendant")
    CABIN_ATTENDANT("CabinAttendant"),
    @XmlEnumValue("LocalCrew")
    LOCAL_CREW("LocalCrew"),
    @XmlEnumValue("Trainee")
    TRAINEE("Trainee"),
    @XmlEnumValue("Observer")
    OBSERVER("Observer"),
    @XmlEnumValue("GroundEngineer")
    GROUND_ENGINEER("GroundEngineer"),
    @XmlEnumValue("AnimalAttendant")
    ANIMAL_ATTENDANT("AnimalAttendant"),
    @XmlEnumValue("SecurityOfficer")
    SECURITY_OFFICER("SecurityOfficer"),
    @XmlEnumValue("AuthorityInspector")
    AUTHORITY_INSPECTOR("AuthorityInspector"),
    @XmlEnumValue("Loadmaster")
    LOADMASTER("Loadmaster"),
    @XmlEnumValue("Doctor")
    DOCTOR("Doctor");
    private final String value;

    RankType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RankType fromValue(String v) {
        for (RankType c: RankType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
