//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RouteDefinitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="LateralRoute" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="RouteWaypoints">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RouteWaypoint" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="Coordinates" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Airway" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="type">
 *                                                 &lt;simpleType>
 *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                     &lt;minLength value="1"/>
 *                                                   &lt;/restriction>
 *                                                 &lt;/simpleType>
 *                                               &lt;/attribute>
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Functions" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Function" maxOccurs="unbounded">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;minLength value="1"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/all>
 *                                     &lt;attribute name="waypointId" type="{http://aeec.aviation-ia.net/633}WaypointIdType" />
 *                                     &lt;attribute name="waypointName">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;minLength value="1"/>
 *                                           &lt;whiteSpace value="preserve"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="countryICAOCode" type="{http://aeec.aviation-ia.net/633}CountryICAOCodeType" />
 *                                     &lt;attribute name="waypointLongName">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;minLength value="1"/>
 *                                           &lt;whiteSpace value="preserve"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VerticalRoute" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Altitudes" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://aeec.aviation-ia.net/633}AltitudeInfoType">
 *                           &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Airports" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Airport" type="{http://aeec.aviation-ia.net/633}AirportIdentificationType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntryConnections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Connection" type="{http://aeec.aviation-ia.net/633}RouteDefinitionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExitConnections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Connection" type="{http://aeec.aviation-ia.net/633}RouteDefinitionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Remarks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Remark" type="{http://aeec.aviation-ia.net/633}TextType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="routeIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="revisionTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="area" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startValidTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="endValidTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="trackApplicability" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteDefinitionType", propOrder = {

})
@XmlSeeAlso({
    com.jeppesen.gs.otsas.xml.OrganizedTracks.OrganizedTracksSet.OrganizedTrack.class
})
public class RouteDefinitionType {

    @XmlElement(name = "LateralRoute")
    protected RouteDefinitionType.LateralRoute lateralRoute;
    @XmlElement(name = "VerticalRoute")
    protected RouteDefinitionType.VerticalRoute verticalRoute;
    @XmlElement(name = "Airports")
    protected RouteDefinitionType.Airports airports;
    @XmlElement(name = "EntryConnections")
    protected RouteDefinitionType.EntryConnections entryConnections;
    @XmlElement(name = "ExitConnections")
    protected RouteDefinitionType.ExitConnections exitConnections;
    @XmlElement(name = "Remarks")
    protected RouteDefinitionType.Remarks remarks;
    @XmlAttribute(name = "routeIdentifier")
    protected String routeIdentifier;
    @XmlAttribute(name = "revisionTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar revisionTime;
    @XmlAttribute(name = "area")
    protected String area;
    @XmlAttribute(name = "startValidTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startValidTime;
    @XmlAttribute(name = "endValidTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endValidTime;
    @XmlAttribute(name = "trackApplicability")
    @XmlSchemaType(name = "anySimpleType")
    protected String trackApplicability;

    /**
     * Gets the value of the lateralRoute property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.LateralRoute }
     *     
     */
    public RouteDefinitionType.LateralRoute getLateralRoute() {
        return lateralRoute;
    }

    /**
     * Sets the value of the lateralRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.LateralRoute }
     *     
     */
    public void setLateralRoute(RouteDefinitionType.LateralRoute value) {
        this.lateralRoute = value;
    }

    /**
     * Gets the value of the verticalRoute property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.VerticalRoute }
     *     
     */
    public RouteDefinitionType.VerticalRoute getVerticalRoute() {
        return verticalRoute;
    }

    /**
     * Sets the value of the verticalRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.VerticalRoute }
     *     
     */
    public void setVerticalRoute(RouteDefinitionType.VerticalRoute value) {
        this.verticalRoute = value;
    }

    /**
     * Gets the value of the airports property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.Airports }
     *     
     */
    public RouteDefinitionType.Airports getAirports() {
        return airports;
    }

    /**
     * Sets the value of the airports property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.Airports }
     *     
     */
    public void setAirports(RouteDefinitionType.Airports value) {
        this.airports = value;
    }

    /**
     * Gets the value of the entryConnections property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.EntryConnections }
     *     
     */
    public RouteDefinitionType.EntryConnections getEntryConnections() {
        return entryConnections;
    }

    /**
     * Sets the value of the entryConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.EntryConnections }
     *     
     */
    public void setEntryConnections(RouteDefinitionType.EntryConnections value) {
        this.entryConnections = value;
    }

    /**
     * Gets the value of the exitConnections property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.ExitConnections }
     *     
     */
    public RouteDefinitionType.ExitConnections getExitConnections() {
        return exitConnections;
    }

    /**
     * Sets the value of the exitConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.ExitConnections }
     *     
     */
    public void setExitConnections(RouteDefinitionType.ExitConnections value) {
        this.exitConnections = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDefinitionType.Remarks }
     *     
     */
    public RouteDefinitionType.Remarks getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDefinitionType.Remarks }
     *     
     */
    public void setRemarks(RouteDefinitionType.Remarks value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the routeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteIdentifier() {
        return routeIdentifier;
    }

    /**
     * Sets the value of the routeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteIdentifier(String value) {
        this.routeIdentifier = value;
    }

    /**
     * Gets the value of the revisionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRevisionTime() {
        return revisionTime;
    }

    /**
     * Sets the value of the revisionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRevisionTime(XMLGregorianCalendar value) {
        this.revisionTime = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArea(String value) {
        this.area = value;
    }

    /**
     * Gets the value of the startValidTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartValidTime() {
        return startValidTime;
    }

    /**
     * Sets the value of the startValidTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartValidTime(XMLGregorianCalendar value) {
        this.startValidTime = value;
    }

    /**
     * Gets the value of the endValidTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndValidTime() {
        return endValidTime;
    }

    /**
     * Sets the value of the endValidTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndValidTime(XMLGregorianCalendar value) {
        this.endValidTime = value;
    }

    /**
     * Gets the value of the trackApplicability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackApplicability() {
        return trackApplicability;
    }

    /**
     * Sets the value of the trackApplicability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackApplicability(String value) {
        this.trackApplicability = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Airport" type="{http://aeec.aviation-ia.net/633}AirportIdentificationType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "airport"
    })
    public static class Airports {

        @XmlElement(name = "Airport", required = true)
        protected List<AirportIdentificationType> airport;

        /**
         * Gets the value of the airport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the airport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAirport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AirportIdentificationType }
         * 
         * 
         */
        public List<AirportIdentificationType> getAirport() {
            if (airport == null) {
                airport = new ArrayList<AirportIdentificationType>();
            }
            return this.airport;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Connection" type="{http://aeec.aviation-ia.net/633}RouteDefinitionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connection"
    })
    public static class EntryConnections {

        @XmlElement(name = "Connection", required = true)
        protected List<RouteDefinitionType> connection;

        /**
         * Gets the value of the connection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the connection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteDefinitionType }
         * 
         * 
         */
        public List<RouteDefinitionType> getConnection() {
            if (connection == null) {
                connection = new ArrayList<RouteDefinitionType>();
            }
            return this.connection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Connection" type="{http://aeec.aviation-ia.net/633}RouteDefinitionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "connection"
    })
    public static class ExitConnections {

        @XmlElement(name = "Connection", required = true)
        protected List<RouteDefinitionType> connection;

        /**
         * Gets the value of the connection property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the connection property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConnection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteDefinitionType }
         * 
         * 
         */
        public List<RouteDefinitionType> getConnection() {
            if (connection == null) {
                connection = new ArrayList<RouteDefinitionType>();
            }
            return this.connection;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="RouteWaypoints">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RouteWaypoint" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="Coordinates" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Airway" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="type">
     *                                       &lt;simpleType>
     *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                           &lt;minLength value="1"/>
     *                                         &lt;/restriction>
     *                                       &lt;/simpleType>
     *                                     &lt;/attribute>
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Functions" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Function" maxOccurs="unbounded">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                             &lt;minLength value="1"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/all>
     *                           &lt;attribute name="waypointId" type="{http://aeec.aviation-ia.net/633}WaypointIdType" />
     *                           &lt;attribute name="waypointName">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;minLength value="1"/>
     *                                 &lt;whiteSpace value="preserve"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="countryICAOCode" type="{http://aeec.aviation-ia.net/633}CountryICAOCodeType" />
     *                           &lt;attribute name="waypointLongName">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;minLength value="1"/>
     *                                 &lt;whiteSpace value="preserve"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class LateralRoute {

        @XmlElement(name = "RouteWaypoints", required = true)
        protected RouteDefinitionType.LateralRoute.RouteWaypoints routeWaypoints;

        /**
         * Gets the value of the routeWaypoints property.
         * 
         * @return
         *     possible object is
         *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints }
         *     
         */
        public RouteDefinitionType.LateralRoute.RouteWaypoints getRouteWaypoints() {
            return routeWaypoints;
        }

        /**
         * Sets the value of the routeWaypoints property.
         * 
         * @param value
         *     allowed object is
         *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints }
         *     
         */
        public void setRouteWaypoints(RouteDefinitionType.LateralRoute.RouteWaypoints value) {
            this.routeWaypoints = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RouteWaypoint" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="Coordinates" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Airway" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="type">
         *                             &lt;simpleType>
         *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                 &lt;minLength value="1"/>
         *                               &lt;/restriction>
         *                             &lt;/simpleType>
         *                           &lt;/attribute>
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Functions" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Function" maxOccurs="unbounded">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                   &lt;minLength value="1"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/all>
         *                 &lt;attribute name="waypointId" type="{http://aeec.aviation-ia.net/633}WaypointIdType" />
         *                 &lt;attribute name="waypointName">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;minLength value="1"/>
         *                       &lt;whiteSpace value="preserve"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="countryICAOCode" type="{http://aeec.aviation-ia.net/633}CountryICAOCodeType" />
         *                 &lt;attribute name="waypointLongName">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;minLength value="1"/>
         *                       &lt;whiteSpace value="preserve"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "routeWaypoint"
        })
        public static class RouteWaypoints {

            @XmlElement(name = "RouteWaypoint", required = true)
            protected List<RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint> routeWaypoint;

            /**
             * Gets the value of the routeWaypoint property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the routeWaypoint property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRouteWaypoint().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint }
             * 
             * 
             */
            public List<RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint> getRouteWaypoint() {
                if (routeWaypoint == null) {
                    routeWaypoint = new ArrayList<RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint>();
                }
                return this.routeWaypoint;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="Coordinates" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Airway" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="type">
             *                   &lt;simpleType>
             *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                       &lt;minLength value="1"/>
             *                     &lt;/restriction>
             *                   &lt;/simpleType>
             *                 &lt;/attribute>
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Functions" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Function" maxOccurs="unbounded">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                         &lt;minLength value="1"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/all>
             *       &lt;attribute name="waypointId" type="{http://aeec.aviation-ia.net/633}WaypointIdType" />
             *       &lt;attribute name="waypointName">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;minLength value="1"/>
             *             &lt;whiteSpace value="preserve"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="countryICAOCode" type="{http://aeec.aviation-ia.net/633}CountryICAOCodeType" />
             *       &lt;attribute name="waypointLongName">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;minLength value="1"/>
             *             &lt;whiteSpace value="preserve"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="sequenceId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class RouteWaypoint {

                @XmlElement(name = "Coordinates")
                protected RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates coordinates;
                @XmlElement(name = "Airway")
                protected RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway airway;
                @XmlElement(name = "Functions")
                protected RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions functions;
                @XmlAttribute(name = "waypointId")
                protected String waypointId;
                @XmlAttribute(name = "waypointName")
                protected String waypointName;
                @XmlAttribute(name = "countryICAOCode")
                protected String countryICAOCode;
                @XmlAttribute(name = "waypointLongName")
                protected String waypointLongName;
                @XmlAttribute(name = "sequenceId")
                @XmlSchemaType(name = "nonNegativeInteger")
                protected BigInteger sequenceId;

                /**
                 * Gets the value of the coordinates property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates }
                 *     
                 */
                public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates getCoordinates() {
                    return coordinates;
                }

                /**
                 * Sets the value of the coordinates property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates }
                 *     
                 */
                public void setCoordinates(RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Coordinates value) {
                    this.coordinates = value;
                }

                /**
                 * Gets the value of the airway property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway }
                 *     
                 */
                public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway getAirway() {
                    return airway;
                }

                /**
                 * Sets the value of the airway property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway }
                 *     
                 */
                public void setAirway(RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Airway value) {
                    this.airway = value;
                }

                /**
                 * Gets the value of the functions property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions }
                 *     
                 */
                public RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions getFunctions() {
                    return functions;
                }

                /**
                 * Sets the value of the functions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions }
                 *     
                 */
                public void setFunctions(RouteDefinitionType.LateralRoute.RouteWaypoints.RouteWaypoint.Functions value) {
                    this.functions = value;
                }

                /**
                 * Gets the value of the waypointId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWaypointId() {
                    return waypointId;
                }

                /**
                 * Sets the value of the waypointId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWaypointId(String value) {
                    this.waypointId = value;
                }

                /**
                 * Gets the value of the waypointName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWaypointName() {
                    return waypointName;
                }

                /**
                 * Sets the value of the waypointName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWaypointName(String value) {
                    this.waypointName = value;
                }

                /**
                 * Gets the value of the countryICAOCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountryICAOCode() {
                    return countryICAOCode;
                }

                /**
                 * Sets the value of the countryICAOCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountryICAOCode(String value) {
                    this.countryICAOCode = value;
                }

                /**
                 * Gets the value of the waypointLongName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWaypointLongName() {
                    return waypointLongName;
                }

                /**
                 * Sets the value of the waypointLongName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWaypointLongName(String value) {
                    this.waypointLongName = value;
                }

                /**
                 * Gets the value of the sequenceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getSequenceId() {
                    return sequenceId;
                }

                /**
                 * Sets the value of the sequenceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setSequenceId(BigInteger value) {
                    this.sequenceId = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="type">
                 *         &lt;simpleType>
                 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *             &lt;minLength value="1"/>
                 *           &lt;/restriction>
                 *         &lt;/simpleType>
                 *       &lt;/attribute>
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Airway {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "type")
                    protected String type;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attGroup ref="{http://aeec.aviation-ia.net/633}coordinateType.grp"/>
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Coordinates {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "latitude", required = true)
                    protected float latitude;
                    @XmlAttribute(name = "longitude", required = true)
                    protected float longitude;
                    @XmlAttribute(name = "magneticVariation")
                    protected Float magneticVariation;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the latitude property.
                     * 
                     */
                    public float getLatitude() {
                        return latitude;
                    }

                    /**
                     * Sets the value of the latitude property.
                     * 
                     */
                    public void setLatitude(float value) {
                        this.latitude = value;
                    }

                    /**
                     * Gets the value of the longitude property.
                     * 
                     */
                    public float getLongitude() {
                        return longitude;
                    }

                    /**
                     * Sets the value of the longitude property.
                     * 
                     */
                    public void setLongitude(float value) {
                        this.longitude = value;
                    }

                    /**
                     * Gets the value of the magneticVariation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getMagneticVariation() {
                        return magneticVariation;
                    }

                    /**
                     * Sets the value of the magneticVariation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setMagneticVariation(Float value) {
                        this.magneticVariation = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Function" maxOccurs="unbounded">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *               &lt;minLength value="1"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "function"
                })
                public static class Functions {

                    @XmlElement(name = "Function", required = true)
                    protected List<String> function;

                    /**
                     * Gets the value of the function property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the function property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getFunction().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getFunction() {
                        if (function == null) {
                            function = new ArrayList<String>();
                        }
                        return this.function;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Remark" type="{http://aeec.aviation-ia.net/633}TextType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "remark"
    })
    public static class Remarks {

        @XmlElement(name = "Remark", required = true)
        protected List<TextType> remark;

        /**
         * Gets the value of the remark property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the remark property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRemark().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TextType }
         * 
         * 
         */
        public List<TextType> getRemark() {
            if (remark == null) {
                remark = new ArrayList<TextType>();
            }
            return this.remark;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Altitudes" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://aeec.aviation-ia.net/633}AltitudeInfoType">
     *                 &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "altitudes"
    })
    public static class VerticalRoute {

        @XmlElement(name = "Altitudes", required = true)
        protected List<RouteDefinitionType.VerticalRoute.Altitudes> altitudes;

        /**
         * Gets the value of the altitudes property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the altitudes property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAltitudes().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteDefinitionType.VerticalRoute.Altitudes }
         * 
         * 
         */
        public List<RouteDefinitionType.VerticalRoute.Altitudes> getAltitudes() {
            if (altitudes == null) {
                altitudes = new ArrayList<RouteDefinitionType.VerticalRoute.Altitudes>();
            }
            return this.altitudes;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://aeec.aviation-ia.net/633}AltitudeInfoType">
         *       &lt;attribute name="direction" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Altitudes
            extends AltitudeInfoType
        {

            @XmlAttribute(name = "direction")
            protected String direction;

            /**
             * Gets the value of the direction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDirection() {
                return direction;
            }

            /**
             * Sets the value of the direction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDirection(String value) {
                this.direction = value;
            }

        }

    }

}
