//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatisticValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatisticValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="percentile90"/>
 *     &lt;enumeration value="percentile95"/>
 *     &lt;enumeration value="percentile99"/>
 *     &lt;enumeration value="MeanValue"/>
 *     &lt;enumeration value="MediumValue"/>
 *     &lt;enumeration value="StandardDeviation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatisticValueType")
@XmlEnum
public enum StatisticValueType {

    @XmlEnumValue("percentile90")
    PERCENTILE_90("percentile90"),
    @XmlEnumValue("percentile95")
    PERCENTILE_95("percentile95"),
    @XmlEnumValue("percentile99")
    PERCENTILE_99("percentile99"),
    @XmlEnumValue("MeanValue")
    MEAN_VALUE("MeanValue"),
    @XmlEnumValue("MediumValue")
    MEDIUM_VALUE("MediumValue"),
    @XmlEnumValue("StandardDeviation")
    STANDARD_DEVIATION("StandardDeviation");
    private final String value;

    StatisticValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatisticValueType fromValue(String v) {
        for (StatisticValueType c: StatisticValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
