//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SurfaceWindType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SurfaceWindType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Directions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Variable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence>
 *                     &lt;element name="Direction" type="{http://aeec.aviation-ia.net/633}DirectionType" minOccurs="0"/>
 *                     &lt;element name="VariableWindRange" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="Direction1" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
 *                               &lt;element name="Direction2" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Speeds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Calm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;sequence>
 *                     &lt;element name="Speed" type="{http://aeec.aviation-ia.net/633}SpeedType"/>
 *                     &lt;element name="Gusts" type="{http://aeec.aviation-ia.net/633}SpeedType" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="runwayIdentifier">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="2"/>
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurfaceWindType", propOrder = {
    "directions",
    "speeds"
})
public class SurfaceWindType {

    @XmlElement(name = "Directions", required = true)
    protected SurfaceWindType.Directions directions;
    @XmlElement(name = "Speeds", required = true)
    protected SurfaceWindType.Speeds speeds;
    @XmlAttribute(name = "runwayIdentifier")
    protected String runwayIdentifier;

    /**
     * Gets the value of the directions property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceWindType.Directions }
     *     
     */
    public SurfaceWindType.Directions getDirections() {
        return directions;
    }

    /**
     * Sets the value of the directions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceWindType.Directions }
     *     
     */
    public void setDirections(SurfaceWindType.Directions value) {
        this.directions = value;
    }

    /**
     * Gets the value of the speeds property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceWindType.Speeds }
     *     
     */
    public SurfaceWindType.Speeds getSpeeds() {
        return speeds;
    }

    /**
     * Sets the value of the speeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceWindType.Speeds }
     *     
     */
    public void setSpeeds(SurfaceWindType.Speeds value) {
        this.speeds = value;
    }

    /**
     * Gets the value of the runwayIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunwayIdentifier() {
        return runwayIdentifier;
    }

    /**
     * Sets the value of the runwayIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunwayIdentifier(String value) {
        this.runwayIdentifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Variable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence>
     *           &lt;element name="Direction" type="{http://aeec.aviation-ia.net/633}DirectionType" minOccurs="0"/>
     *           &lt;element name="VariableWindRange" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="Direction1" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
     *                     &lt;element name="Direction2" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "variable",
        "direction",
        "variableWindRange"
    })
    public static class Directions {

        @XmlElement(name = "Variable")
        protected String variable;
        @XmlElement(name = "Direction")
        protected DirectionType direction;
        @XmlElement(name = "VariableWindRange")
        protected SurfaceWindType.Directions.VariableWindRange variableWindRange;

        /**
         * Gets the value of the variable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariable() {
            return variable;
        }

        /**
         * Sets the value of the variable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariable(String value) {
            this.variable = value;
        }

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link DirectionType }
         *     
         */
        public DirectionType getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link DirectionType }
         *     
         */
        public void setDirection(DirectionType value) {
            this.direction = value;
        }

        /**
         * Gets the value of the variableWindRange property.
         * 
         * @return
         *     possible object is
         *     {@link SurfaceWindType.Directions.VariableWindRange }
         *     
         */
        public SurfaceWindType.Directions.VariableWindRange getVariableWindRange() {
            return variableWindRange;
        }

        /**
         * Sets the value of the variableWindRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link SurfaceWindType.Directions.VariableWindRange }
         *     
         */
        public void setVariableWindRange(SurfaceWindType.Directions.VariableWindRange value) {
            this.variableWindRange = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Direction1" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
         *         &lt;element name="Direction2" type="{http://aeec.aviation-ia.net/633}DirectionType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "direction1",
            "direction2"
        })
        public static class VariableWindRange {

            @XmlElement(name = "Direction1", required = true)
            protected DirectionType direction1;
            @XmlElement(name = "Direction2", required = true)
            protected DirectionType direction2;

            /**
             * Gets the value of the direction1 property.
             * 
             * @return
             *     possible object is
             *     {@link DirectionType }
             *     
             */
            public DirectionType getDirection1() {
                return direction1;
            }

            /**
             * Sets the value of the direction1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link DirectionType }
             *     
             */
            public void setDirection1(DirectionType value) {
                this.direction1 = value;
            }

            /**
             * Gets the value of the direction2 property.
             * 
             * @return
             *     possible object is
             *     {@link DirectionType }
             *     
             */
            public DirectionType getDirection2() {
                return direction2;
            }

            /**
             * Sets the value of the direction2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link DirectionType }
             *     
             */
            public void setDirection2(DirectionType value) {
                this.direction2 = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Calm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;sequence>
     *           &lt;element name="Speed" type="{http://aeec.aviation-ia.net/633}SpeedType"/>
     *           &lt;element name="Gusts" type="{http://aeec.aviation-ia.net/633}SpeedType" minOccurs="0"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calm",
        "speed",
        "gusts"
    })
    public static class Speeds {

        @XmlElement(name = "Calm")
        protected String calm;
        @XmlElement(name = "Speed")
        protected SpeedType speed;
        @XmlElement(name = "Gusts")
        protected SpeedType gusts;

        /**
         * Gets the value of the calm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalm() {
            return calm;
        }

        /**
         * Sets the value of the calm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalm(String value) {
            this.calm = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         * @return
         *     possible object is
         *     {@link SpeedType }
         *     
         */
        public SpeedType getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpeedType }
         *     
         */
        public void setSpeed(SpeedType value) {
            this.speed = value;
        }

        /**
         * Gets the value of the gusts property.
         * 
         * @return
         *     possible object is
         *     {@link SpeedType }
         *     
         */
        public SpeedType getGusts() {
            return gusts;
        }

        /**
         * Sets the value of the gusts property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpeedType }
         *     
         */
        public void setGusts(SpeedType value) {
            this.gusts = value;
        }

    }

}
