//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for thunderstormTrendType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="thunderstormTrendType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="developing"/>
 *     &lt;enumeration value="developed"/>
 *     &lt;enumeration value="diminishing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "thunderstormTrendType")
@XmlEnum
public enum ThunderstormTrendType {

    @XmlEnumValue("developing")
    DEVELOPING("developing"),
    @XmlEnumValue("developed")
    DEVELOPED("developed"),
    @XmlEnumValue("diminishing")
    DIMINISHING("diminishing");
    private final String value;

    ThunderstormTrendType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ThunderstormTrendType fromValue(String v) {
        for (ThunderstormTrendType c: ThunderstormTrendType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
