//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * horizontal visibility
 * 
 * <p>Java class for VisibilityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisibilityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrevailingVisibility" type="{http://aeec.aviation-ia.net/633}DistanceType"/>
 *         &lt;element name="MinimumVisibility" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
 *                 &lt;attribute name="direction">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="N"/>
 *                       &lt;enumeration value="NNE"/>
 *                       &lt;enumeration value="NE"/>
 *                       &lt;enumeration value="ENE"/>
 *                       &lt;enumeration value="E"/>
 *                       &lt;enumeration value="ESE"/>
 *                       &lt;enumeration value="SE"/>
 *                       &lt;enumeration value="SSE"/>
 *                       &lt;enumeration value="S"/>
 *                       &lt;enumeration value="SSW"/>
 *                       &lt;enumeration value="SW"/>
 *                       &lt;enumeration value="WSW"/>
 *                       &lt;enumeration value="W"/>
 *                       &lt;enumeration value="WNW"/>
 *                       &lt;enumeration value="NW"/>
 *                       &lt;enumeration value="NNW"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaximumVisibility" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
 *                 &lt;attribute name="direction">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="N"/>
 *                       &lt;enumeration value="NNE"/>
 *                       &lt;enumeration value="NE"/>
 *                       &lt;enumeration value="ENE"/>
 *                       &lt;enumeration value="E"/>
 *                       &lt;enumeration value="ESE"/>
 *                       &lt;enumeration value="SE"/>
 *                       &lt;enumeration value="SSE"/>
 *                       &lt;enumeration value="S"/>
 *                       &lt;enumeration value="SSW"/>
 *                       &lt;enumeration value="SW"/>
 *                       &lt;enumeration value="WSW"/>
 *                       &lt;enumeration value="W"/>
 *                       &lt;enumeration value="WNW"/>
 *                       &lt;enumeration value="NW"/>
 *                       &lt;enumeration value="NNW"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisibilityType", propOrder = {
    "prevailingVisibility",
    "minimumVisibility",
    "maximumVisibility"
})
public class VisibilityType {

    @XmlElement(name = "PrevailingVisibility", required = true)
    protected DistanceType prevailingVisibility;
    @XmlElement(name = "MinimumVisibility")
    protected VisibilityType.MinimumVisibility minimumVisibility;
    @XmlElement(name = "MaximumVisibility")
    protected VisibilityType.MaximumVisibility maximumVisibility;

    /**
     * Gets the value of the prevailingVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link DistanceType }
     *     
     */
    public DistanceType getPrevailingVisibility() {
        return prevailingVisibility;
    }

    /**
     * Sets the value of the prevailingVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistanceType }
     *     
     */
    public void setPrevailingVisibility(DistanceType value) {
        this.prevailingVisibility = value;
    }

    /**
     * Gets the value of the minimumVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilityType.MinimumVisibility }
     *     
     */
    public VisibilityType.MinimumVisibility getMinimumVisibility() {
        return minimumVisibility;
    }

    /**
     * Sets the value of the minimumVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilityType.MinimumVisibility }
     *     
     */
    public void setMinimumVisibility(VisibilityType.MinimumVisibility value) {
        this.minimumVisibility = value;
    }

    /**
     * Gets the value of the maximumVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilityType.MaximumVisibility }
     *     
     */
    public VisibilityType.MaximumVisibility getMaximumVisibility() {
        return maximumVisibility;
    }

    /**
     * Sets the value of the maximumVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilityType.MaximumVisibility }
     *     
     */
    public void setMaximumVisibility(VisibilityType.MaximumVisibility value) {
        this.maximumVisibility = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
     *       &lt;attribute name="direction">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="N"/>
     *             &lt;enumeration value="NNE"/>
     *             &lt;enumeration value="NE"/>
     *             &lt;enumeration value="ENE"/>
     *             &lt;enumeration value="E"/>
     *             &lt;enumeration value="ESE"/>
     *             &lt;enumeration value="SE"/>
     *             &lt;enumeration value="SSE"/>
     *             &lt;enumeration value="S"/>
     *             &lt;enumeration value="SSW"/>
     *             &lt;enumeration value="SW"/>
     *             &lt;enumeration value="WSW"/>
     *             &lt;enumeration value="W"/>
     *             &lt;enumeration value="WNW"/>
     *             &lt;enumeration value="NW"/>
     *             &lt;enumeration value="NNW"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MaximumVisibility
        extends DistanceType
    {

        @XmlAttribute(name = "direction")
        protected String direction;

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDirection(String value) {
            this.direction = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://aeec.aviation-ia.net/633}DistanceType">
     *       &lt;attribute name="direction">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="N"/>
     *             &lt;enumeration value="NNE"/>
     *             &lt;enumeration value="NE"/>
     *             &lt;enumeration value="ENE"/>
     *             &lt;enumeration value="E"/>
     *             &lt;enumeration value="ESE"/>
     *             &lt;enumeration value="SE"/>
     *             &lt;enumeration value="SSE"/>
     *             &lt;enumeration value="S"/>
     *             &lt;enumeration value="SSW"/>
     *             &lt;enumeration value="SW"/>
     *             &lt;enumeration value="WSW"/>
     *             &lt;enumeration value="W"/>
     *             &lt;enumeration value="WNW"/>
     *             &lt;enumeration value="NW"/>
     *             &lt;enumeration value="NNW"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MinimumVisibility
        extends DistanceType
    {

        @XmlAttribute(name = "direction")
        protected String direction;

        /**
         * Gets the value of the direction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDirection() {
            return direction;
        }

        /**
         * Sets the value of the direction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDirection(String value) {
            this.direction = value;
        }

    }

}
