//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for volumeUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="volumeUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="l"/>
 *     &lt;enumeration value="ug"/>
 *     &lt;enumeration value="ig"/>
 *     &lt;enumeration value="m3"/>
 *     &lt;enumeration value="cm3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "volumeUnitType")
@XmlEnum
public enum VolumeUnitType {

    @XmlEnumValue("l")
    L("l"),
    @XmlEnumValue("ug")
    UG("ug"),
    @XmlEnumValue("ig")
    IG("ig"),
    @XmlEnumValue("m3")
    M_3("m3"),
    @XmlEnumValue("cm3")
    CM_3("cm3");
    private final String value;

    VolumeUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeUnitType fromValue(String v) {
        for (VolumeUnitType c: VolumeUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
