//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * weather description and type, e.g. BLSN for blowing snow, FZFG for freezing fog 
 * 
 * <p>Java class for WeatherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="intensity" use="required" type="{http://aeec.aviation-ia.net/633}airportWeatherIntensityProximityType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherType")
@XmlSeeAlso({
    com.jeppesen.gs.otsas.xml.VisibilitiesAndWeatherType.Weather.class,
    com.jeppesen.gs.otsas.xml.ObservationDetailsType.SupplementaryInformation.RecentWeather.class
})
public class WeatherType {

    @XmlAttribute(name = "intensity", required = true)
    protected AirportWeatherIntensityProximityType intensity;

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link AirportWeatherIntensityProximityType }
     *     
     */
    public AirportWeatherIntensityProximityType getIntensity() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportWeatherIntensityProximityType }
     *     
     */
    public void setIntensity(AirportWeatherIntensityProximityType value) {
        this.intensity = value;
    }

}
