//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for WeatherChangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeatherChangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SurfaceWind" type="{http://aeec.aviation-ia.net/633}SurfaceWindType" minOccurs="0"/>
 *         &lt;element name="VisibilitiesAndWeather" type="{http://aeec.aviation-ia.net/633}VisibilitiesAndWeatherType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="becoming" type="{http://www.w3.org/2001/XMLSchema}string" fixed="BECMG" />
 *       &lt;attribute name="temporary" type="{http://www.w3.org/2001/XMLSchema}string" fixed="TEMPO" />
 *       &lt;attribute name="at" type="{http://www.w3.org/2001/XMLSchema}string" fixed="AT" />
 *       &lt;attribute name="from" type="{http://www.w3.org/2001/XMLSchema}string" fixed="FM" />
 *       &lt;attribute name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="until" type="{http://www.w3.org/2001/XMLSchema}string" fixed="TL" />
 *       &lt;attribute name="endTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="probability" type="{http://aeec.aviation-ia.net/633}probabilityType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeatherChangeType", propOrder = {
    "surfaceWind",
    "visibilitiesAndWeather"
})
public class WeatherChangeType {

    @XmlElement(name = "SurfaceWind")
    protected SurfaceWindType surfaceWind;
    @XmlElement(name = "VisibilitiesAndWeather")
    protected VisibilitiesAndWeatherType visibilitiesAndWeather;
    @XmlAttribute(name = "becoming")
    protected String becoming;
    @XmlAttribute(name = "temporary")
    protected String temporary;
    @XmlAttribute(name = "at")
    protected String at;
    @XmlAttribute(name = "from")
    protected String from;
    @XmlAttribute(name = "startTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "until")
    protected String until;
    @XmlAttribute(name = "endTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlAttribute(name = "probability")
    protected String probability;

    /**
     * Gets the value of the surfaceWind property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceWindType }
     *     
     */
    public SurfaceWindType getSurfaceWind() {
        return surfaceWind;
    }

    /**
     * Sets the value of the surfaceWind property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceWindType }
     *     
     */
    public void setSurfaceWind(SurfaceWindType value) {
        this.surfaceWind = value;
    }

    /**
     * Gets the value of the visibilitiesAndWeather property.
     * 
     * @return
     *     possible object is
     *     {@link VisibilitiesAndWeatherType }
     *     
     */
    public VisibilitiesAndWeatherType getVisibilitiesAndWeather() {
        return visibilitiesAndWeather;
    }

    /**
     * Sets the value of the visibilitiesAndWeather property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibilitiesAndWeatherType }
     *     
     */
    public void setVisibilitiesAndWeather(VisibilitiesAndWeatherType value) {
        this.visibilitiesAndWeather = value;
    }

    /**
     * Gets the value of the becoming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBecoming() {
        if (becoming == null) {
            return "BECMG";
        } else {
            return becoming;
        }
    }

    /**
     * Sets the value of the becoming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBecoming(String value) {
        this.becoming = value;
    }

    /**
     * Gets the value of the temporary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporary() {
        if (temporary == null) {
            return "TEMPO";
        } else {
            return temporary;
        }
    }

    /**
     * Sets the value of the temporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporary(String value) {
        this.temporary = value;
    }

    /**
     * Gets the value of the at property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAt() {
        if (at == null) {
            return "AT";
        } else {
            return at;
        }
    }

    /**
     * Sets the value of the at property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAt(String value) {
        this.at = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        if (from == null) {
            return "FM";
        } else {
            return from;
        }
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the until property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUntil() {
        if (until == null) {
            return "TL";
        } else {
            return until;
        }
    }

    /**
     * Sets the value of the until property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUntil(String value) {
        this.until = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the probability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProbability(String value) {
        this.probability = value;
    }

}
