//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:32:25 AM MDT 
//


package com.jeppesen.gs.otsas.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for weightUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="weightUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kg"/>
 *     &lt;enumeration value="t"/>
 *     &lt;enumeration value="lb"/>
 *     &lt;enumeration value="hlb"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "weightUnitType")
@XmlEnum
public enum WeightUnitType {

    @XmlEnumValue("kg")
    KG("kg"),
    @XmlEnumValue("t")
    T("t"),
    @XmlEnumValue("lb")
    LB("lb"),
    @XmlEnumValue("hlb")
    HLB("hlb");
    private final String value;

    WeightUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WeightUnitType fromValue(String v) {
        for (WeightUnitType c: WeightUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
